"""### 📦 Тестовый пакет xStream / TFS

Загружает тестовые ZIP-пакеты в S3 с актуальными таймштампами.
Данные фиксированы (3 части, 36/37/38 строк), меняется только таймштамп.

| Параметр       | Описание                                              |
|----------------|-------------------------------------------------------|
| `prefix`       | Префикс имени файла *(default: hrplatform_datalab)*           |
| `table_name`   | Таблица в формате schema__table *(default: learning__lc_items_opened)* |
| `s3_prefix`    | Папка в бакете *(default: from/KAP802/...)*                   |
| `bucket`       | S3 бакет *(default: edpetl-test)*                             |
| `conn_id`      | Airflow S3 connection *(default: s3-archive)*                 |
"""

from __future__ import annotations
import base64
import zipfile
from io import BytesIO

import pendulum
from airflow.decorators import dag, task
from airflow.models import Param
from airflow.providers.amazon.aws.hooks.s3 import S3Hook


_META = "eyJzY2hlbWFfbmFtZSI6ImxlYXJuaW5nIiwidGFibGVfbmFtZSI6ImxjX2l0ZW1zX29wZW5lZCIsInN0cmF0ZWd5IjoiRlVMTF9VSyIsIlBLIjpbXSwiVUsiOlsicGVyc29uX3V1aWQiLCJpdGVtX2lkIl0sInBhcmFtcyI6eyJzZXBhcmF0aW9uIjoiXHQiLCJlc2NhcGVzeW1ib2wiOiJcIiJ9LCJjb2x1bW5zIjpbeyJjb2x1bW5fbmFtZSI6ImV4cG9ydF90aW1lIiwic291cmNlX3R5cGUiOiJUSU1FU1RBTVAiLCJsZW5ndGgiOm51bGwsIm5vdG51bGwiOmZhbHNlLCJwcmVjaXNpb24iOm51bGwsInNjYWxlIjpudWxsLCJkZXNjcmlwdGlvbiI6ItCU0LDRgtCwINCy0YvQs9GA0YPQt9C60LgifSx7ImNvbHVtbl9uYW1lIjoiaW5zZXJ0X3RpbWUiLCJzb3VyY2VfdHlwZSI6IlRJTUVTVEFNUCIsImxlbmd0aCI6bnVsbCwibm90bnVsbCI6ZmFsc2UsInByZWNpc2lvbiI6bnVsbCwic2NhbGUiOm51bGwsImRlc2NyaXB0aW9uIjoi0JTQsNGC0LAg0LLRgdGC0LDQstC60LgifSx7ImNvbHVtbl9uYW1lIjoiaGVhZGVyX2lkIiwic291cmNlX3R5cGUiOiJTVFJJTkciLCJsZW5ndGgiOm51bGwsIm5vdG51bGwiOmZhbHNlLCJwcmVjaXNpb24iOjM4LCJzY2FsZSI6MTAsImRlc2NyaXB0aW9uIjoi0KPQvdC40LrQsNC70YzQvdGL0Lkg0LjQtNC10L3RgtC40YTQuNC60LDRgtC+0YAg0LjQstC10L3RgtCwIn0seyJjb2x1bW5fbmFtZSI6ImhlYWRlcl9wZXJzb25faWQiLCJzb3VyY2VfdHlwZSI6IlNUUklORyIsImxlbmd0aCI6NDA5Niwibm90bnVsbCI6ZmFsc2UsInByZWNpc2lvbiI6bnVsbCwic2NhbGUiOm51bGwsImRlc2NyaXB0aW9uIjoiSUQg0YHQvtGC0YDRg9C00L3QuNC60LAsINC40LfRg9GH0LDRjtGJ0LXQs9C+INC80LDRgtC10YDQuNCw0LsifSx7ImNvbHVtbl9uYW1lIjoiaGVhZGVyX2V2ZW50X3R5cGUiLCJzb3VyY2VfdHlwZSI6IlNUUklORyIsImxlbmd0aCI6NDA5Niwibm90bnVsbCI6ZmFsc2UsInByZWNpc2lvbiI6bnVsbCwic2NhbGUiOm51bGwsImRlc2NyaXB0aW9uIjoi0KLQuNC/INC40LLQtdC90YLQsCJ9LHsiY29sdW1uX25hbWUiOiJoZWFkZXJfY3JlYXRlZF9kdCIsInNvdXJjZV90eXBlIjoiREFURSIsImxlbmd0aCI6NDA5Niwibm90bnVsbCI6ZmFsc2UsInByZWNpc2lvbiI6bnVsbCwic2NhbGUiOm51bGwsImRlc2NyaXB0aW9uIjoi0JTQsNGC0LAg0LPQtdC90LXRgNCw0YbQuNC4INC40LLQtdC90YLQsCJ9LHsiY29sdW1uX25hbWUiOiJpdGVtX2lkIiwic291cmNlX3R5cGUiOiJJTlQiLCJsZW5ndGgiOjI1LCJub3RudWxsIjp0cnVlLCJwcmVjaXNpb24iOm51bGwsInNjYWxlIjpudWxsLCJkZXNjcmlwdGlvbiI6IklEINC80LDRgtC10YDQuNCw0LvQsCJ9LHsiY29sdW1uX25hbWUiOiJwZXJzb25fdXVpZCIsInNvdXJjZV90eXBlIjoiSU5UIiwibGVuZ3RoIjoyNSwibm90bnVsbCI6dHJ1ZSwicHJlY2lzaW9uIjpudWxsLCJzY2FsZSI6bnVsbCwiZGVzY3JpcHRpb24iOiJJRCDRgdC+0YLRgNGD0LTQvdC40LrQsCwg0LjQt9GD0YfQsNGO0YnQtdCz0L4g0LzQsNGC0LXRgNC40LDQuyJ9LHsiY29sdW1uX25hbWUiOiJ0ZW5hbnQiLCJzb3VyY2VfdHlwZSI6IlNUUklORyIsImxlbmd0aCI6NDA5Niwibm90bnVsbCI6ZmFsc2UsInByZWNpc2lvbiI6bnVsbCwic2NhbGUiOm51bGwsImRlc2NyaXB0aW9uIjoi0YLQtdC90LDQvdGCIn0seyJjb2x1bW5fbmFtZSI6ImNvbXBhbnkiLCJzb3VyY2VfdHlwZSI6IlNUUklORyIsImxlbmd0aCI6NDA5Niwibm90bnVsbCI6ZmFsc2UsInByZWNpc2lvbiI6bnVsbCwic2NhbGUiOm51bGwsImRlc2NyaXB0aW9uIjoi0LrQvtC80L/QsNC90LjRjyJ9LHsiY29sdW1uX25hbWUiOiJjdGxfYWN0aW9uIiwic291cmNlX3R5cGUiOiJWQVJDSEFSIiwibGVuZ3RoIjoxMCwibm90bnVsbCI6ZmFsc2UsInByZWNpc2lvbiI6bnVsbCwic2NhbGUiOm51bGwsImRlc2NyaXB0aW9uIjpudWxsfSx7ImNvbHVtbl9uYW1lIjoiY3RsX3ZhbGlkZnJvbSIsInNvdXJjZV90eXBlIjoiVElNRVNUQU1QIiwibGVuZ3RoIjpudWxsLCJub3RudWxsIjpmYWxzZSwicHJlY2lzaW9uIjpudWxsLCJzY2FsZSI6bnVsbCwiZGVzY3JpcHRpb24iOm51bGx9XX0="

# (base64-encoded CSV bytes, row_count)
_PARTS: list[tuple[str, int]] = [
    (
        "ZXhwb3J0X3RpbWUJaW5zZXJ0X3RpbWUJaGVhZGVyX2lkCWhlYWRlcl9wZXJzb25faWQJaGVhZGVyX2V2ZW50X3R5cGUJaGVhZGVy"
        "X2NyZWF0ZWRfZHQJaXRlbV9pZAlwZXJzb25fdXVpZAl0ZW5hbnQJY29tcGFueQljdGxfYWN0aW9uCWN0bF92YWxpZGZyb20KMjAy"
        "Ni0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDEyOjQ4OjQzCTA5ZGI5MThiLWZkODAtNGFmYS1hNzFiLTY2ZmQzNTRiNTIxMgll"
        "YTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAwOTo0Nzo0Mwkx"
        "ZDUxYmU1MC1kZTllLTQxMmMtOWViOC0yMDg1ZmJiZmQ4NDAJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlCXNi"
        "ZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0"
        "LTAzIDIwOjExOjMwCTBjYjg1NDgxLTY4M2YtNDdhNS1iY2NhLTlmYjIxYmI3YTZmMwkJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0w"
        "NC0wMyAxNzoxMDoxMAlkYTQxNWZiYS1kODk0LTQ4ZWItYWVmNS04ZWE3ZDhmODZkNmEJZWMwNzhmNWYtNTI5My00ZjVjLTlhYzAt"
        "ZjhlMTYyMTJlOTYxCQkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEg"
        "MTM6NTk6MTgJMTI5YjJlNjMtNjBlMC00OTBhLWE3YjItZTk2Mjc4ZGE2Y2VmCTEwNmYyOWVhLTRjZDUtNDJmMy05OWQ5LTQ2YzFi"
        "OGUwZjMyMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDEwOjU4OjA5CTc1YzExNTFjLTQyYTItNDljNC05MGYwLWZhMDA4"
        "ZTFkNzllMAkxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjIJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0"
        "LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTQ6Mjk6MDgJMTI5YjczODUtODkxMS00"
        "NDczLWE3MzEtMjRkYmFlNGZmNDYxCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDExOjI3OjMxCWY4ZDgyNTg5LTJmNGUt"
        "NGQ4NS1hMjA4LTI3MzA0ZmVmYzA3MAllZjA4YjZmMi0zNDkyLTRmMGItOTM2MC1hMmRiZjM4MmI4MTAJCQlJCTIwMjYtMDQtMDcg"
        "MTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxMDoxNjoyMwkyNTk5ZGVjMC1jMjc1LTQ2ZTUt"
        "YTE0OS0wZGY0MGZmN2UwYTAJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDIgMDc6MTU6MTUJMjI0OTJhOTMtNzk3Yi00NGJi"
        "LTlmYmMtZTM5ZTM4Yjk2NDgwCWE3Y2VhMjBlLTQxYjEtNGUzZC04OGYyLWNlNDA2MjA5ZDZhZAkJCUkJMjAyNi0wNC0wNyAxMDo0"
        "NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAyIDE2OjQ4OjA5CTJjMjA3MWI2LWExMzEtNGY4Yy1iNjhi"
        "LTI1OWM0Y2UyZGQxNgk2ODA4ODBlNS1kOTY4LTRlNWItODY0MC01YTQwNDhhMWRlNzQJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0w"
        "NC0wMiAxMzozNzo0MwllNTQxNmQ3My02Y2ZjLTQ5NDUtYjkwMS1mYTQ2YmViOGE5MTAJNjgwODgwZTUtZDk2OC00ZTViLTg2NDAt"
        "NWE0MDQ4YTFkZTc0CXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAx"
        "MDoxNzoxNQkyMDI2LTA0LTAxIDE0OjMyOjA3CTJlY2IwMzk2LTYzMjctNDRiYi05YzJmLTM4ZDc3NWVmNTQyNQkJQ2F0YWxvZ0l0"
        "ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMTozMDo0NwlmOGQ4MjU4OS0yZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzAJZWYwOGI2ZjIt"
        "MzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCQkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3"
        "OjE1CTIwMjYtMDQtMDIgMDk6MTY6NDgJMzE0ZTUxMjUtYWYyMC00NWU5LTk3YWUtZTEyNDQwZWU2YTRjCTMzMzk1NTJiLTAxMmIt"
        "NDMwMi1iMzMxLTEyOTIyOWM1OGVlZQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjE2OjA0CWU3ZThhNjRiLTJhNWEt"
        "NDkxYS1iMzBlLTE1OTc2YTJmMzkwMAkzMzM5NTUyYi0wMTJiLTQzMDItYjMzMS0xMjkyMjljNThlZWUJc2JlcmJhbmsJcGFvc2Jl"
        "cmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMTI6NTQ6NTQJ"
        "MzU2MGI4YjEtNzgzMy00NmI0LWJhNjMtMGJiYjI4ODE0NTgzCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA5OjU0OjIz"
        "CTk1YTY2M2RjLTFmMDctNDEyYy1iNjZjLTVhNTQ1Y2EyZDRhYQlhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWQJ"
        "CQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxNzoxNzoyMgk1NGRl"
        "NDYzNy1kZDM3LTQ5ODctOTQ3ZS03OGRkYzBhOGY0NDgJMGJjMzNiZWEtMDg3Yi00NTZkLThiZWYtNjliOTNlOWM0OTQ2CUNhdGFs"
        "b2dJdGVtT3BlbmVkCTIwMjYtMDQtMDIgMTQ6MTA6MDQJZjBkODVjNzctMWU2Ny00N2FjLWE0MDItMTQ5N2I5NjI2ZjhiCTBiYzMz"
        "YmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0NglzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIu"
        "MDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAxOTo1MzozMwk1N2M2OGQ3Yy02ODZlLTQ0ZDMtYmM3Yi1kNjg2"
        "ZTc0OTM4ZDgJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTY6NTI6MDgJNTYwOWNiYWQtYTI0My00NGUyLWI2MDItNjdj"
        "NDc3NGI2ZjgwCTlmODZlZjZjLTY4ZDUtNDcwMS05MzI4LWI0ZWUwNDc1MGE3MAkJCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAx"
        "MTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDEzOjU5OjE0CTVlY2QzNmNlLTViMjAtNDMyZC05ODU3LWVlYjdhMjQ3"
        "OWU1YwllYTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMDo1"
        "NjozNAk2YzAwYjlhNy1lYWRkLTRmMWEtOTMwNS05ZmJmOGY5MDI4OTQJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3"
        "YWVlCXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQky"
        "MDI2LTA0LTAxIDE0OjI3OjA2CTYzZTFkYTdmLTNiZGUtNDFhMS05NzFmLTEyY2ZiYjBlMTFmMwllZjA4YjZmMi0zNDkyLTRmMGIt"
        "OTM2MC1hMmRiZjM4MmI4MTAJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMToyNTo0OQk4ZjQ1NDVlYS1jNzFhLTRmZTUt"
        "OTczZi0zMjk1YTBlZjk1NzkJZWYwOGI2ZjItMzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCXNiZXJiYW5rCXBhb3NiZXJiYW5r"
        "CUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDE0OjMzOjM1CTZlY2Nm"
        "YjI4LWQ3Y2ItNDQxNy04Mzk0LWEzMjNkY2JjNDNhZQkJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMTozMjowMAlmOGQ4"
        "MjU4OS0yZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzAJZWYwOGI2ZjItMzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCQkJSQky"
        "MDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTY6MDk6MTQJN2FhNTFkM2Ut"
        "ODFhNy00M2U1LTgxMTYtM2MwM2U1OTlmM2IxCTViN2UwZWE2LWM1MGYtNDYxNy1hZDRjLTRjMGYwMjYwMjMwOAlDYXRhbG9nSXRl"
        "bU9wZW5lZAkyMDI2LTA0LTAzIDEzOjA3OjE1CTc1YzExNTFjLTQyYTItNDljNC05MGYwLWZhMDA4ZTFkNzllMAk1YjdlMGVhNi1j"
        "NTBmLTQ2MTctYWQ0Yy00YzBmMDI2MDIzMDgJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDEx"
        "MgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDYgMTg6MjY6MTUJN2I4ZmNhMzctMGY2OS00ZWZhLTlhYTctYWQzNDIwMjRh"
        "OGNhCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTA2IDE1OjI1"
        "OjM3CTNkNGExZTA5LThkMTAtNGFmOS1iNjhkLTJiNWJmZDhiNDBkMAliN2NhMGQ1Mi0xOGY4LTQ3NzEtOWIxZC02MDI1ZTZmMDNh"
        "MjkJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIw"
        "MjYtMDQtMDIgMTM6MDM6NTUJODFjM2ZjNzUtODc2YS00ZmJjLThmNGYtMmNhNWIyZmEyODBkCTMzMzk1NTJiLTAxMmItNDMwMi1i"
        "MzMxLTEyOTIyOWM1OGVlZQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDEwOjAzOjA2CWVlYjU0NjE2LWJmYzItNDdiOC05"
        "YmYyLWRjMDczY2VjNjc4NQkzMzM5NTUyYi0wMTJiLTQzMDItYjMzMS0xMjkyMjljNThlZWUJc2JlcmJhbmsJcGFvc2JlcmJhbmsJ"
        "SQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMDk6NTk6MDUJODRjY2U0"
        "NzEtOTQ3NS00ZTlmLWI3NzktYmI5MjFjZDAwMTJlCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjU4OjAzCTk1YTY2"
        "M2RjLTFmMDctNDEyYy1iNjZjLTVhNTQ1Y2EyZDRhYQlhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWQJCQlJCTIw"
        "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAyMDoxMTo0OAk5NWNhNGVjZC1l"
        "NzVlLTRiNjMtYmY1YS02MTFiN2Y1YzY1NDkJNWQzOGQxYzYtMzkxNy00MDRmLTg3YzktN2U4YTk2NDJkNmY5CUNhdGFsb2dJdGVt"
        "T3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MzAJMmE0NGY5MjQtMTljZi00NmRhLThkNTAtNGY2Y2EyNzBhMGQzCTVkMzhkMWM2LTM5"
        "MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOQlzYmVyYmFuawkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3"
        "IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTQ6MzQ6MDEJOTY5OTI2ZDMtYmRmYy00Mzk4LWEyZDQtYTFjZTcxNzE2NmM3CWM1MDVkZTA3"
        "LWI4ODctNDE2ZS04NjhlLTdhODEwZjE2NDMwMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDExOjMzOjA5CTRkNDg5ZDhj"
        "LWJjZjMtNDJkOS05YTFhLTBlMzUwMTI0MDc4YQljNTA1ZGUwNy1iODg3LTQxNmUtODY4ZS03YTgxMGYxNjQzMDIJc2JlcmJhbmsJ"
        "cGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTM6"
        "NTc6MjcJOWFhNzEyYTctNDZiOC00ZmY5LThmNjQtMDVkOTZkNDU0NzNjCTEwNmYyOWVhLTRjZDUtNDJmMy05OWQ5LTQ2YzFiOGUw"
        "ZjMyMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDEwOjU1OjMzCTZjMDBiOWE3LWVhZGQtNGYxYS05MzA1LTlmYmY4Zjkw"
        "Mjg5NAkxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjIJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3"
        "IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMDk6Mzg6NDMJOWVjYzkxYzQtYTU4MC00Y2Jm"
        "LTgyM2UtNTE5MzU0ZTc5YTYwCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjM3OjQxCTk1YTY2M2RjLTFmMDctNDEy"
        "Yy1iNjZjLTVhNTQ1Y2EyZDRhYQlkYTk5YTQzNi0xZGM1LTRhODYtOTUxZC1lODczN2Y5MWI4ZmQJCQlJCTIwMjYtMDQtMDcgMTA6"
        "NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMSAxNDoyNDowMwk5ZmE1NjhlYS02Njk1LTRmYmUtOWRl"
        "MC1iZTU5OTM4Mzk0YWEJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDEgMTE6MjI6MDEJZjhkODI1ODktMmY0ZS00ZDg1LWEy"
        "MDgtMjczMDRmZWZjMDcwCWVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMAkJCUkJMjAyNi0wNC0wNyAxMDo0NDow"
        "Mi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAzIDE5OjUzOjMzCWEwZjE4YTc5LTYwODItNGUxMC1iNDcwLWE3"
        "YzgyNjc4N2JkNwk0NjQ4MzdkNi01YzRmLTQ4MWQtYmUwNy00YWI5OTkzMTdiZGYJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0w"
        "MyAxNjo1Mjo1NAkyYTQ0ZjkyNC0xOWNmLTQ2ZGEtOGQ1MC00ZjZjYTI3MGEwZDMJNDY0ODM3ZDYtNWM0Zi00ODFkLWJlMDctNGFi"
        "OTk5MzE3YmRmCXNiZXJiYW5rCQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0w"
        "NC0wMyAxNjoyNDozNwlhMzIyMjRmYS1hOTU0LTRlYjktOWY3OC0wNmRjNzFkODU3MDYJYjdjYTBkNTItMThmOC00NzcxLTliMWQt"
        "NjAyNWU2ZjAzYTI5CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTM6MjM6NTIJYWIzYTdhN2UtYWQ0Yy00MTBmLTkxNjct"
        "Zjg3NDBlMjUzOWRlCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOQlzYmVyYmFuawkJSQkyMDI2LTA0LTA3IDEw"
        "OjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTk6NTM6MzMJYTY0ZTBhN2MtNWExZS00ZTAzLWE5"
        "MzYtNjBhMDk0ZGViZjNjCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAzIDE2OjUyOjUyCWRhNDE1ZmJhLWQ4OTQtNDhlYi1h"
        "ZWY1LThlYTdkOGY4NmQ2YQk0NjQ4MzdkNi01YzRmLTQ4MWQtYmUwNy00YWI5OTkzMTdiZGYJCQlJCTIwMjYtMDQtMDcgMTA6NDQ6"
        "MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxMzo0NDo1NwlhYjk3MmMyYy04ZDE2LTRhY2YtOWU2MC1m"
        "ZmVjOWJjZmQyOTYJYjdjYTBkNTItMThmOC00NzcxLTliMWQtNjAyNWU2ZjAzYTI5CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQt"
        "MDIgMTA6NDQ6NDYJMzA0M2M1OGUtZTgzNS00OGMxLWI5ZDMtMGVkZWMxMzhmODMyCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYw"
        "MjVlNmYwM2EyOQlzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6"
        "MTc6MTUJMjAyNi0wNC0wMyAyMDoxMToyNgliYzg5YjU5MS1iMDdmLTRkZDAtYTgzOC1mMTQxZjNiNjRkMzEJZWMwNzhmNWYtNTI5"
        "My00ZjVjLTlhYzAtZjhlMTYyMTJlOTYxCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MTIJMmE0NGY5MjQtMTlj"
        "Zi00NmRhLThkNTAtNGY2Y2EyNzBhMGQzCWVjMDc4ZjVmLTUyOTMtNGY1Yy05YWMwLWY4ZTE2MjEyZTk2MQlzYmVyYmFuawkJSQky"
        "MDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTI6Mjk6MjgJY2UwNDI0NWIt"
        "ODZhYS00M2NiLTg5Y2ItOTg3OTUxZTMwNjRjCWVhNjg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZQlDYXRhbG9nSXRl"
        "bU9wZW5lZAkyMDI2LTA0LTAxIDA5OjI4OjQ2CWIzMWUwM2I0LTZkZTYtNDMzYy1hNzg2LWE5ODk0NjVkYTQyZAllYTY4OThhOS02"
        "MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDEx"
        "MgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTE6MjM6MzYJZDljYjExZjAtZmE1OC00ZmMzLTg1OTMtMzllZmNlYjZj"
        "MzllCWNhNjBlMzIzLTkwNWMtNGQ5Ny1iNGQ1LWRlYmU2NWUzMTk4ZAlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAzIDA4OjIx"
        "OjAyCWRiNGNmYmRjLWMyMTYtNGZhNy05NmI2LTZkYmU0NTNjZjA3YwljYTYwZTMyMy05MDVjLTRkOTctYjRkNS1kZWJlNjVlMzE5"
        "OGQJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIw"
        "MjYtMDQtMDYgMTY6NDA6NDIJZGM4MWQ3ZWEtMWNjNi00NDk1LThhNzYtMDA2MWU2YjdjYTY4CTBiYzMzYmVhLTA4N2ItNDU2ZC04"
        "YmVmLTY5YjkzZTljNDk0NglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTA2IDEzOjQwOjIxCWZkZDdhMGUwLTkyN2EtNDQ4OS04"
        "OWFkLTcxNmFlYzhiZjc0YwkwYmMzM2JlYS0wODdiLTQ1NmQtOGJlZi02OWI5M2U5YzQ5NDYJc2JlcmJhbmsJCUkJMjAyNi0wNC0w"
        "NyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAzIDE5OjU0OjIxCWU2MDliYWMyLWIyMzctNDhh"
        "Yy05NDY3LWVmN2U2NmJiZTRiMAk5Zjg2ZWY2Yy02OGQ1LTQ3MDEtOTMyOC1iNGVlMDQ3NTBhNzAJQ2F0YWxvZ0l0ZW1PcGVuZWQJ"
        "MjAyNi0wNC0wMyAxNjo1MzozNgkyYTQ0ZjkyNC0xOWNmLTQ2ZGEtOGQ1MC00ZjZjYTI3MGEwZDMJOWY4NmVmNmMtNjhkNS00NzAx"
        "LTkzMjgtYjRlZTA0NzUwYTcwCXNiZXJiYW5rCQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6"
        "MTUJMjAyNi0wNC0wNiAxNjo0NjozMwllNmRiNWZjZS1hZTUxLTQ4MGQtYWJlNS03ODIwMmRkOWJmZGUJMGJjMzNiZWEtMDg3Yi00"
        "NTZkLThiZWYtNjliOTNlOWM0OTQ2CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDYgMTM6NDU6NDgJMmFkZGFlNTgtZDRkNi00"
        "ZmM5LWEzMDYtMmI5OTMzOGFlMTI3CTBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0NglzYmVyYmFuawlwYW9zYmVy"
        "YmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAxNjowOTo0NQll"
        "YzBlMmRlMS1hZDY5LTQ2ODAtYjMxMC1jYjYxYzk1NDBlOWEJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlCUNh"
        "dGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTM6MDc6MjkJNzVjMTE1MWMtNDJhMi00OWM0LTkwZjAtZmEwMDhlMWQ3OWUwCWVh"
        "Njg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZQlzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6"
        "MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAyMDoxMjowMQllZDMxOTNjMy0wZTdlLTQ2YTQtOWQ1Zi1m"
        "NTJhZDVjN2Q5OTAJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MjkJNTYwOWNiYWQtYTI0My00NGUyLWI2MDIt"
        "NjdjNDc3NGI2ZjgwCTVkMzhkMWM2LTM5MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOQkJCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4w"
        "MDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTA2IDEyOjExOjE1CWYxNGYzNmU0LTBlODktNDQ5NS05YWVhLWI5OTYy"
        "MGViYWNhYgkyMjhkNDYwNC1hZDJjLTRmNjQtOGYzZS00NzE4YjZlNjA4NWYJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wNiAw"
        "OToxMDowNwk2YjQzMjIwNi1mMzA4LTQwNWYtOTU2Yi1jZjIyNTgwNjk3YmUJMjI4ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2"
        "ZTYwODVmCXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIK",
        36,
    ),
    (
        "ZXhwb3J0X3RpbWUJaW5zZXJ0X3RpbWUJaGVhZGVyX2lkCWhlYWRlcl9wZXJzb25faWQJaGVhZGVyX2V2ZW50X3R5cGUJaGVhZGVy"
        "X2NyZWF0ZWRfZHQJaXRlbV9pZAlwZXJzb25fdXVpZAl0ZW5hbnQJY29tcGFueQljdGxfYWN0aW9uCWN0bF92YWxpZGZyb20KMjAy"
        "Ni0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDEyOjQ4OjQzCTA5ZGI5MThiLWZkODAtNGFmYS1hNzFiLTY2ZmQzNTRiNTIxMgll"
        "YTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAwOTo0Nzo0Mwkx"
        "ZDUxYmU1MC1kZTllLTQxMmMtOWViOC0yMDg1ZmJiZmQ4NDAJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlCXNi"
        "ZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0"
        "LTAzIDIwOjExOjMwCTBjYjg1NDgxLTY4M2YtNDdhNS1iY2NhLTlmYjIxYmI3YTZmMwkJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0w"
        "NC0wMyAxNzoxMDoxMAlkYTQxNWZiYS1kODk0LTQ4ZWItYWVmNS04ZWE3ZDhmODZkNmEJZWMwNzhmNWYtNTI5My00ZjVjLTlhYzAt"
        "ZjhlMTYyMTJlOTYxCQkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEg"
        "MTM6NTk6MTgJMTI5YjJlNjMtNjBlMC00OTBhLWE3YjItZTk2Mjc4ZGE2Y2VmCTEwNmYyOWVhLTRjZDUtNDJmMy05OWQ5LTQ2YzFi"
        "OGUwZjMyMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDEwOjU4OjA5CTc1YzExNTFjLTQyYTItNDljNC05MGYwLWZhMDA4"
        "ZTFkNzllMAkxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjIJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0"
        "LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTQ6Mjk6MDgJMTI5YjczODUtODkxMS00"
        "NDczLWE3MzEtMjRkYmFlNGZmNDYxCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDExOjI3OjMxCWY4ZDgyNTg5LTJmNGUt"
        "NGQ4NS1hMjA4LTI3MzA0ZmVmYzA3MAllZjA4YjZmMi0zNDkyLTRmMGItOTM2MC1hMmRiZjM4MmI4MTAJCQlJCTIwMjYtMDQtMDcg"
        "MTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxMDoxNjoyMwkyNTk5ZGVjMC1jMjc1LTQ2ZTUt"
        "YTE0OS0wZGY0MGZmN2UwYTAJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDIgMDc6MTU6MTUJMjI0OTJhOTMtNzk3Yi00NGJi"
        "LTlmYmMtZTM5ZTM4Yjk2NDgwCWE3Y2VhMjBlLTQxYjEtNGUzZC04OGYyLWNlNDA2MjA5ZDZhZAkJCUkJMjAyNi0wNC0wNyAxMDo0"
        "NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAyIDE2OjQ4OjA5CTJjMjA3MWI2LWExMzEtNGY4Yy1iNjhi"
        "LTI1OWM0Y2UyZGQxNgk2ODA4ODBlNS1kOTY4LTRlNWItODY0MC01YTQwNDhhMWRlNzQJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0w"
        "NC0wMiAxMzozNzo0MwllNTQxNmQ3My02Y2ZjLTQ5NDUtYjkwMS1mYTQ2YmViOGE5MTAJNjgwODgwZTUtZDk2OC00ZTViLTg2NDAt"
        "NWE0MDQ4YTFkZTc0CXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAx"
        "MDoxNzoxNQkyMDI2LTA0LTAxIDE0OjMyOjA3CTJlY2IwMzk2LTYzMjctNDRiYi05YzJmLTM4ZDc3NWVmNTQyNQkJQ2F0YWxvZ0l0"
        "ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMTozMDo0NwlmOGQ4MjU4OS0yZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzAJZWYwOGI2ZjIt"
        "MzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCQkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3"
        "OjE1CTIwMjYtMDQtMDIgMDk6MTY6NDgJMzE0ZTUxMjUtYWYyMC00NWU5LTk3YWUtZTEyNDQwZWU2YTRjCTMzMzk1NTJiLTAxMmIt"
        "NDMwMi1iMzMxLTEyOTIyOWM1OGVlZQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjE2OjA0CWU3ZThhNjRiLTJhNWEt"
        "NDkxYS1iMzBlLTE1OTc2YTJmMzkwMAkzMzM5NTUyYi0wMTJiLTQzMDItYjMzMS0xMjkyMjljNThlZWUJc2JlcmJhbmsJcGFvc2Jl"
        "cmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMTI6NTQ6NTQJ"
        "MzU2MGI4YjEtNzgzMy00NmI0LWJhNjMtMGJiYjI4ODE0NTgzCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA5OjU0OjIz"
        "CTk1YTY2M2RjLTFmMDctNDEyYy1iNjZjLTVhNTQ1Y2EyZDRhYQlhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWQJ"
        "CQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxNzoxNzoyMgk1NGRl"
        "NDYzNy1kZDM3LTQ5ODctOTQ3ZS03OGRkYzBhOGY0NDgJMGJjMzNiZWEtMDg3Yi00NTZkLThiZWYtNjliOTNlOWM0OTQ2CUNhdGFs"
        "b2dJdGVtT3BlbmVkCTIwMjYtMDQtMDIgMTQ6MTA6MDQJZjBkODVjNzctMWU2Ny00N2FjLWE0MDItMTQ5N2I5NjI2ZjhiCTBiYzMz"
        "YmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0NglzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIu"
        "MDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAxOTo1MzozMwk1N2M2OGQ3Yy02ODZlLTQ0ZDMtYmM3Yi1kNjg2"
        "ZTc0OTM4ZDgJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTY6NTI6MDgJNTYwOWNiYWQtYTI0My00NGUyLWI2MDItNjdj"
        "NDc3NGI2ZjgwCTlmODZlZjZjLTY4ZDUtNDcwMS05MzI4LWI0ZWUwNDc1MGE3MAkJCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAx"
        "MTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDEzOjU5OjE0CTVlY2QzNmNlLTViMjAtNDMyZC05ODU3LWVlYjdhMjQ3"
        "OWU1YwllYTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMDo1"
        "NjozNAk2YzAwYjlhNy1lYWRkLTRmMWEtOTMwNS05ZmJmOGY5MDI4OTQJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3"
        "YWVlCXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQky"
        "MDI2LTA0LTAxIDE0OjI3OjA2CTYzZTFkYTdmLTNiZGUtNDFhMS05NzFmLTEyY2ZiYjBlMTFmMwllZjA4YjZmMi0zNDkyLTRmMGIt"
        "OTM2MC1hMmRiZjM4MmI4MTAJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMToyNTo0OQk4ZjQ1NDVlYS1jNzFhLTRmZTUt"
        "OTczZi0zMjk1YTBlZjk1NzkJZWYwOGI2ZjItMzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCXNiZXJiYW5rCXBhb3NiZXJiYW5r"
        "CUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDE0OjMzOjM1CTZlY2Nm"
        "YjI4LWQ3Y2ItNDQxNy04Mzk0LWEzMjNkY2JjNDNhZQkJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMTozMjowMAlmOGQ4"
        "MjU4OS0yZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzAJZWYwOGI2ZjItMzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCQkJSQky"
        "MDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTY6MDk6MTQJN2FhNTFkM2Ut"
        "ODFhNy00M2U1LTgxMTYtM2MwM2U1OTlmM2IxCTViN2UwZWE2LWM1MGYtNDYxNy1hZDRjLTRjMGYwMjYwMjMwOAlDYXRhbG9nSXRl"
        "bU9wZW5lZAkyMDI2LTA0LTAzIDEzOjA3OjE1CTc1YzExNTFjLTQyYTItNDljNC05MGYwLWZhMDA4ZTFkNzllMAk1YjdlMGVhNi1j"
        "NTBmLTQ2MTctYWQ0Yy00YzBmMDI2MDIzMDgJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDEx"
        "MgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDYgMTg6MjY6MTUJN2I4ZmNhMzctMGY2OS00ZWZhLTlhYTctYWQzNDIwMjRh"
        "OGNhCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTA2IDE1OjI1"
        "OjM3CTNkNGExZTA5LThkMTAtNGFmOS1iNjhkLTJiNWJmZDhiNDBkMAliN2NhMGQ1Mi0xOGY4LTQ3NzEtOWIxZC02MDI1ZTZmMDNh"
        "MjkJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIw"
        "MjYtMDQtMDIgMTM6MDM6NTUJODFjM2ZjNzUtODc2YS00ZmJjLThmNGYtMmNhNWIyZmEyODBkCTMzMzk1NTJiLTAxMmItNDMwMi1i"
        "MzMxLTEyOTIyOWM1OGVlZQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDEwOjAzOjA2CWVlYjU0NjE2LWJmYzItNDdiOC05"
        "YmYyLWRjMDczY2VjNjc4NQkzMzM5NTUyYi0wMTJiLTQzMDItYjMzMS0xMjkyMjljNThlZWUJc2JlcmJhbmsJcGFvc2JlcmJhbmsJ"
        "SQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMDk6NTk6MDUJODRjY2U0"
        "NzEtOTQ3NS00ZTlmLWI3NzktYmI5MjFjZDAwMTJlCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjU4OjAzCTk1YTY2"
        "M2RjLTFmMDctNDEyYy1iNjZjLTVhNTQ1Y2EyZDRhYQlhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWQJCQlJCTIw"
        "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAyMDoxMTo0OAk5NWNhNGVjZC1l"
        "NzVlLTRiNjMtYmY1YS02MTFiN2Y1YzY1NDkJNWQzOGQxYzYtMzkxNy00MDRmLTg3YzktN2U4YTk2NDJkNmY5CUNhdGFsb2dJdGVt"
        "T3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MzAJMmE0NGY5MjQtMTljZi00NmRhLThkNTAtNGY2Y2EyNzBhMGQzCTVkMzhkMWM2LTM5"
        "MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOQlzYmVyYmFuawkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3"
        "IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTQ6MzQ6MDEJOTY5OTI2ZDMtYmRmYy00Mzk4LWEyZDQtYTFjZTcxNzE2NmM3CWM1MDVkZTA3"
        "LWI4ODctNDE2ZS04NjhlLTdhODEwZjE2NDMwMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDExOjMzOjA5CTRkNDg5ZDhj"
        "LWJjZjMtNDJkOS05YTFhLTBlMzUwMTI0MDc4YQljNTA1ZGUwNy1iODg3LTQxNmUtODY4ZS03YTgxMGYxNjQzMDIJc2JlcmJhbmsJ"
        "cGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTM6"
        "NTc6MjcJOWFhNzEyYTctNDZiOC00ZmY5LThmNjQtMDVkOTZkNDU0NzNjCTEwNmYyOWVhLTRjZDUtNDJmMy05OWQ5LTQ2YzFiOGUw"
        "ZjMyMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDEwOjU1OjMzCTZjMDBiOWE3LWVhZGQtNGYxYS05MzA1LTlmYmY4Zjkw"
        "Mjg5NAkxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjIJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3"
        "IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMDk6Mzg6NDMJOWVjYzkxYzQtYTU4MC00Y2Jm"
        "LTgyM2UtNTE5MzU0ZTc5YTYwCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjM3OjQxCTk1YTY2M2RjLTFmMDctNDEy"
        "Yy1iNjZjLTVhNTQ1Y2EyZDRhYQlkYTk5YTQzNi0xZGM1LTRhODYtOTUxZC1lODczN2Y5MWI4ZmQJCQlJCTIwMjYtMDQtMDcgMTA6"
        "NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMSAxNDoyNDowMwk5ZmE1NjhlYS02Njk1LTRmYmUtOWRl"
        "MC1iZTU5OTM4Mzk0YWEJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDEgMTE6MjI6MDEJZjhkODI1ODktMmY0ZS00ZDg1LWEy"
        "MDgtMjczMDRmZWZjMDcwCWVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMAkJCUkJMjAyNi0wNC0wNyAxMDo0NDow"
        "Mi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAzIDE5OjUzOjMzCWEwZjE4YTc5LTYwODItNGUxMC1iNDcwLWE3"
        "YzgyNjc4N2JkNwk0NjQ4MzdkNi01YzRmLTQ4MWQtYmUwNy00YWI5OTkzMTdiZGYJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0w"
        "MyAxNjo1Mjo1NAkyYTQ0ZjkyNC0xOWNmLTQ2ZGEtOGQ1MC00ZjZjYTI3MGEwZDMJNDY0ODM3ZDYtNWM0Zi00ODFkLWJlMDctNGFi"
        "OTk5MzE3YmRmCXNiZXJiYW5rCQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0w"
        "NC0wMyAxNjoyNDozNwlhMzIyMjRmYS1hOTU0LTRlYjktOWY3OC0wNmRjNzFkODU3MDYJYjdjYTBkNTItMThmOC00NzcxLTliMWQt"
        "NjAyNWU2ZjAzYTI5CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTM6MjM6NTIJYWIzYTdhN2UtYWQ0Yy00MTBmLTkxNjct"
        "Zjg3NDBlMjUzOWRlCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOQlzYmVyYmFuawkJSQkyMDI2LTA0LTA3IDEw"
        "OjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTk6NTM6MzMJYTY0ZTBhN2MtNWExZS00ZTAzLWE5"
        "MzYtNjBhMDk0ZGViZjNjCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAzIDE2OjUyOjUyCWRhNDE1ZmJhLWQ4OTQtNDhlYi1h"
        "ZWY1LThlYTdkOGY4NmQ2YQk0NjQ4MzdkNi01YzRmLTQ4MWQtYmUwNy00YWI5OTkzMTdiZGYJCQlJCTIwMjYtMDQtMDcgMTA6NDQ6"
        "MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxMzo0NDo1NwlhYjk3MmMyYy04ZDE2LTRhY2YtOWU2MC1m"
        "ZmVjOWJjZmQyOTYJYjdjYTBkNTItMThmOC00NzcxLTliMWQtNjAyNWU2ZjAzYTI5CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQt"
        "MDIgMTA6NDQ6NDYJMzA0M2M1OGUtZTgzNS00OGMxLWI5ZDMtMGVkZWMxMzhmODMyCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYw"
        "MjVlNmYwM2EyOQlzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6"
        "MTc6MTUJMjAyNi0wNC0wMyAyMDoxMToyNgliYzg5YjU5MS1iMDdmLTRkZDAtYTgzOC1mMTQxZjNiNjRkMzEJZWMwNzhmNWYtNTI5"
        "My00ZjVjLTlhYzAtZjhlMTYyMTJlOTYxCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MTIJMmE0NGY5MjQtMTlj"
        "Zi00NmRhLThkNTAtNGY2Y2EyNzBhMGQzCWVjMDc4ZjVmLTUyOTMtNGY1Yy05YWMwLWY4ZTE2MjEyZTk2MQlzYmVyYmFuawkJSQky"
        "MDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTI6Mjk6MjgJY2UwNDI0NWIt"
        "ODZhYS00M2NiLTg5Y2ItOTg3OTUxZTMwNjRjCWVhNjg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZQlDYXRhbG9nSXRl"
        "bU9wZW5lZAkyMDI2LTA0LTAxIDA5OjI4OjQ2CWIzMWUwM2I0LTZkZTYtNDMzYy1hNzg2LWE5ODk0NjVkYTQyZAllYTY4OThhOS02"
        "MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDEx"
        "MgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTE6MjM6MzYJZDljYjExZjAtZmE1OC00ZmMzLTg1OTMtMzllZmNlYjZj"
        "MzllCWNhNjBlMzIzLTkwNWMtNGQ5Ny1iNGQ1LWRlYmU2NWUzMTk4ZAlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAzIDA4OjIx"
        "OjAyCWRiNGNmYmRjLWMyMTYtNGZhNy05NmI2LTZkYmU0NTNjZjA3YwljYTYwZTMyMy05MDVjLTRkOTctYjRkNS1kZWJlNjVlMzE5"
        "OGQJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIw"
        "MjYtMDQtMDYgMTY6NDA6NDIJZGM4MWQ3ZWEtMWNjNi00NDk1LThhNzYtMDA2MWU2YjdjYTY4CTBiYzMzYmVhLTA4N2ItNDU2ZC04"
        "YmVmLTY5YjkzZTljNDk0NglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTA2IDEzOjQwOjIxCWZkZDdhMGUwLTkyN2EtNDQ4OS04"
        "OWFkLTcxNmFlYzhiZjc0YwkwYmMzM2JlYS0wODdiLTQ1NmQtOGJlZi02OWI5M2U5YzQ5NDYJc2JlcmJhbmsJCUkJMjAyNi0wNC0w"
        "NyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAzIDE5OjU0OjIxCWU2MDliYWMyLWIyMzctNDhh"
        "Yy05NDY3LWVmN2U2NmJiZTRiMAk5Zjg2ZWY2Yy02OGQ1LTQ3MDEtOTMyOC1iNGVlMDQ3NTBhNzAJQ2F0YWxvZ0l0ZW1PcGVuZWQJ"
        "MjAyNi0wNC0wMyAxNjo1MzozNgkyYTQ0ZjkyNC0xOWNmLTQ2ZGEtOGQ1MC00ZjZjYTI3MGEwZDMJOWY4NmVmNmMtNjhkNS00NzAx"
        "LTkzMjgtYjRlZTA0NzUwYTcwCXNiZXJiYW5rCQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6"
        "MTUJMjAyNi0wNC0wNiAxNjo0NjozMwllNmRiNWZjZS1hZTUxLTQ4MGQtYWJlNS03ODIwMmRkOWJmZGUJMGJjMzNiZWEtMDg3Yi00"
        "NTZkLThiZWYtNjliOTNlOWM0OTQ2CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDYgMTM6NDU6NDgJMmFkZGFlNTgtZDRkNi00"
        "ZmM5LWEzMDYtMmI5OTMzOGFlMTI3CTBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0NglzYmVyYmFuawlwYW9zYmVy"
        "YmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAxNjowOTo0NQll"
        "YzBlMmRlMS1hZDY5LTQ2ODAtYjMxMC1jYjYxYzk1NDBlOWEJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlCUNh"
        "dGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTM6MDc6MjkJNzVjMTE1MWMtNDJhMi00OWM0LTkwZjAtZmEwMDhlMWQ3OWUwCWVh"
        "Njg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZQlzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6"
        "MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAyMDoxMjowMQllZDMxOTNjMy0wZTdlLTQ2YTQtOWQ1Zi1m"
        "NTJhZDVjN2Q5OTAJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MjkJNTYwOWNiYWQtYTI0My00NGUyLWI2MDIt"
        "NjdjNDc3NGI2ZjgwCTVkMzhkMWM2LTM5MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOQkJCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4w"
        "MDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTA2IDEyOjExOjE1CWYxNGYzNmU0LTBlODktNDQ5NS05YWVhLWI5OTYy"
        "MGViYWNhYgkyMjhkNDYwNC1hZDJjLTRmNjQtOGYzZS00NzE4YjZlNjA4NWYJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wNiAw"
        "OToxMDowNwk2YjQzMjIwNi1mMzA4LTQwNWYtOTU2Yi1jZjIyNTgwNjk3YmUJMjI4ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2"
        "ZTYwODVmCXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzox"
        "NgkyMDI2LTA0LTA2IDEyOjExOjE1CWYxNGYzNmU0LTBlODktNDQ5NS05YWVhLWI5OTYyMGViYWNhYgkyMjhkNDYwNC1hZDJjLTRm"
        "NjQtOGYzZS00NzE4YjZlNjA4NWYJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wNiAwOToxMDowNwk2YjQzMjIwNi1mMzA4LTQw"
        "NWYtOTU2Yi1jZjIyNTgwNjk3YmUJMjI4ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2ZTYwODVmCXNiZXJiYW5rCXBhb3NiZXJi"
        "YW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIK",
        37,
    ),
    (
        "ZXhwb3J0X3RpbWUJaW5zZXJ0X3RpbWUJaGVhZGVyX2lkCWhlYWRlcl9wZXJzb25faWQJaGVhZGVyX2V2ZW50X3R5cGUJaGVhZGVy"
        "X2NyZWF0ZWRfZHQJaXRlbV9pZAlwZXJzb25fdXVpZAl0ZW5hbnQJY29tcGFueQljdGxfYWN0aW9uCWN0bF92YWxpZGZyb20KMjAy"
        "Ni0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDEyOjQ4OjQzCTA5ZGI5MThiLWZkODAtNGFmYS1hNzFiLTY2ZmQzNTRiNTIxMgll"
        "YTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAwOTo0Nzo0Mwkx"
        "ZDUxYmU1MC1kZTllLTQxMmMtOWViOC0yMDg1ZmJiZmQ4NDAJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlCXNi"
        "ZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0"
        "LTAzIDIwOjExOjMwCTBjYjg1NDgxLTY4M2YtNDdhNS1iY2NhLTlmYjIxYmI3YTZmMwkJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0w"
        "NC0wMyAxNzoxMDoxMAlkYTQxNWZiYS1kODk0LTQ4ZWItYWVmNS04ZWE3ZDhmODZkNmEJZWMwNzhmNWYtNTI5My00ZjVjLTlhYzAt"
        "ZjhlMTYyMTJlOTYxCQkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEg"
        "MTM6NTk6MTgJMTI5YjJlNjMtNjBlMC00OTBhLWE3YjItZTk2Mjc4ZGE2Y2VmCTEwNmYyOWVhLTRjZDUtNDJmMy05OWQ5LTQ2YzFi"
        "OGUwZjMyMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDEwOjU4OjA5CTc1YzExNTFjLTQyYTItNDljNC05MGYwLWZhMDA4"
        "ZTFkNzllMAkxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjIJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0"
        "LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTQ6Mjk6MDgJMTI5YjczODUtODkxMS00"
        "NDczLWE3MzEtMjRkYmFlNGZmNDYxCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDExOjI3OjMxCWY4ZDgyNTg5LTJmNGUt"
        "NGQ4NS1hMjA4LTI3MzA0ZmVmYzA3MAllZjA4YjZmMi0zNDkyLTRmMGItOTM2MC1hMmRiZjM4MmI4MTAJCQlJCTIwMjYtMDQtMDcg"
        "MTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxMDoxNjoyMwkyNTk5ZGVjMC1jMjc1LTQ2ZTUt"
        "YTE0OS0wZGY0MGZmN2UwYTAJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDIgMDc6MTU6MTUJMjI0OTJhOTMtNzk3Yi00NGJi"
        "LTlmYmMtZTM5ZTM4Yjk2NDgwCWE3Y2VhMjBlLTQxYjEtNGUzZC04OGYyLWNlNDA2MjA5ZDZhZAkJCUkJMjAyNi0wNC0wNyAxMDo0"
        "NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAyIDE2OjQ4OjA5CTJjMjA3MWI2LWExMzEtNGY4Yy1iNjhi"
        "LTI1OWM0Y2UyZGQxNgk2ODA4ODBlNS1kOTY4LTRlNWItODY0MC01YTQwNDhhMWRlNzQJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0w"
        "NC0wMiAxMzozNzo0MwllNTQxNmQ3My02Y2ZjLTQ5NDUtYjkwMS1mYTQ2YmViOGE5MTAJNjgwODgwZTUtZDk2OC00ZTViLTg2NDAt"
        "NWE0MDQ4YTFkZTc0CXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAx"
        "MDoxNzoxNQkyMDI2LTA0LTAxIDE0OjMyOjA3CTJlY2IwMzk2LTYzMjctNDRiYi05YzJmLTM4ZDc3NWVmNTQyNQkJQ2F0YWxvZ0l0"
        "ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMTozMDo0NwlmOGQ4MjU4OS0yZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzAJZWYwOGI2ZjIt"
        "MzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCQkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3"
        "OjE1CTIwMjYtMDQtMDIgMDk6MTY6NDgJMzE0ZTUxMjUtYWYyMC00NWU5LTk3YWUtZTEyNDQwZWU2YTRjCTMzMzk1NTJiLTAxMmIt"
        "NDMwMi1iMzMxLTEyOTIyOWM1OGVlZQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjE2OjA0CWU3ZThhNjRiLTJhNWEt"
        "NDkxYS1iMzBlLTE1OTc2YTJmMzkwMAkzMzM5NTUyYi0wMTJiLTQzMDItYjMzMS0xMjkyMjljNThlZWUJc2JlcmJhbmsJcGFvc2Jl"
        "cmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMTI6NTQ6NTQJ"
        "MzU2MGI4YjEtNzgzMy00NmI0LWJhNjMtMGJiYjI4ODE0NTgzCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA5OjU0OjIz"
        "CTk1YTY2M2RjLTFmMDctNDEyYy1iNjZjLTVhNTQ1Y2EyZDRhYQlhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWQJ"
        "CQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxNzoxNzoyMgk1NGRl"
        "NDYzNy1kZDM3LTQ5ODctOTQ3ZS03OGRkYzBhOGY0NDgJMGJjMzNiZWEtMDg3Yi00NTZkLThiZWYtNjliOTNlOWM0OTQ2CUNhdGFs"
        "b2dJdGVtT3BlbmVkCTIwMjYtMDQtMDIgMTQ6MTA6MDQJZjBkODVjNzctMWU2Ny00N2FjLWE0MDItMTQ5N2I5NjI2ZjhiCTBiYzMz"
        "YmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0NglzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIu"
        "MDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAxOTo1MzozMwk1N2M2OGQ3Yy02ODZlLTQ0ZDMtYmM3Yi1kNjg2"
        "ZTc0OTM4ZDgJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTY6NTI6MDgJNTYwOWNiYWQtYTI0My00NGUyLWI2MDItNjdj"
        "NDc3NGI2ZjgwCTlmODZlZjZjLTY4ZDUtNDcwMS05MzI4LWI0ZWUwNDc1MGE3MAkJCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAx"
        "MTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDEzOjU5OjE0CTVlY2QzNmNlLTViMjAtNDMyZC05ODU3LWVlYjdhMjQ3"
        "OWU1YwllYTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMDo1"
        "NjozNAk2YzAwYjlhNy1lYWRkLTRmMWEtOTMwNS05ZmJmOGY5MDI4OTQJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3"
        "YWVlCXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQky"
        "MDI2LTA0LTAxIDE0OjI3OjA2CTYzZTFkYTdmLTNiZGUtNDFhMS05NzFmLTEyY2ZiYjBlMTFmMwllZjA4YjZmMi0zNDkyLTRmMGIt"
        "OTM2MC1hMmRiZjM4MmI4MTAJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMToyNTo0OQk4ZjQ1NDVlYS1jNzFhLTRmZTUt"
        "OTczZi0zMjk1YTBlZjk1NzkJZWYwOGI2ZjItMzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCXNiZXJiYW5rCXBhb3NiZXJiYW5r"
        "CUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAxIDE0OjMzOjM1CTZlY2Nm"
        "YjI4LWQ3Y2ItNDQxNy04Mzk0LWEzMjNkY2JjNDNhZQkJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wMSAxMTozMjowMAlmOGQ4"
        "MjU4OS0yZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzAJZWYwOGI2ZjItMzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwCQkJSQky"
        "MDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTY6MDk6MTQJN2FhNTFkM2Ut"
        "ODFhNy00M2U1LTgxMTYtM2MwM2U1OTlmM2IxCTViN2UwZWE2LWM1MGYtNDYxNy1hZDRjLTRjMGYwMjYwMjMwOAlDYXRhbG9nSXRl"
        "bU9wZW5lZAkyMDI2LTA0LTAzIDEzOjA3OjE1CTc1YzExNTFjLTQyYTItNDljNC05MGYwLWZhMDA4ZTFkNzllMAk1YjdlMGVhNi1j"
        "NTBmLTQ2MTctYWQ0Yy00YzBmMDI2MDIzMDgJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDEx"
        "MgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDYgMTg6MjY6MTUJN2I4ZmNhMzctMGY2OS00ZWZhLTlhYTctYWQzNDIwMjRh"
        "OGNhCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTA2IDE1OjI1"
        "OjM3CTNkNGExZTA5LThkMTAtNGFmOS1iNjhkLTJiNWJmZDhiNDBkMAliN2NhMGQ1Mi0xOGY4LTQ3NzEtOWIxZC02MDI1ZTZmMDNh"
        "MjkJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIw"
        "MjYtMDQtMDIgMTM6MDM6NTUJODFjM2ZjNzUtODc2YS00ZmJjLThmNGYtMmNhNWIyZmEyODBkCTMzMzk1NTJiLTAxMmItNDMwMi1i"
        "MzMxLTEyOTIyOWM1OGVlZQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDEwOjAzOjA2CWVlYjU0NjE2LWJmYzItNDdiOC05"
        "YmYyLWRjMDczY2VjNjc4NQkzMzM5NTUyYi0wMTJiLTQzMDItYjMzMS0xMjkyMjljNThlZWUJc2JlcmJhbmsJcGFvc2JlcmJhbmsJ"
        "SQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMDk6NTk6MDUJODRjY2U0"
        "NzEtOTQ3NS00ZTlmLWI3NzktYmI5MjFjZDAwMTJlCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjU4OjAzCTk1YTY2"
        "M2RjLTFmMDctNDEyYy1iNjZjLTVhNTQ1Y2EyZDRhYQlhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWQJCQlJCTIw"
        "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAyMDoxMTo0OAk5NWNhNGVjZC1l"
        "NzVlLTRiNjMtYmY1YS02MTFiN2Y1YzY1NDkJNWQzOGQxYzYtMzkxNy00MDRmLTg3YzktN2U4YTk2NDJkNmY5CUNhdGFsb2dJdGVt"
        "T3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MzAJMmE0NGY5MjQtMTljZi00NmRhLThkNTAtNGY2Y2EyNzBhMGQzCTVkMzhkMWM2LTM5"
        "MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOQlzYmVyYmFuawkJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3"
        "IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTQ6MzQ6MDEJOTY5OTI2ZDMtYmRmYy00Mzk4LWEyZDQtYTFjZTcxNzE2NmM3CWM1MDVkZTA3"
        "LWI4ODctNDE2ZS04NjhlLTdhODEwZjE2NDMwMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDExOjMzOjA5CTRkNDg5ZDhj"
        "LWJjZjMtNDJkOS05YTFhLTBlMzUwMTI0MDc4YQljNTA1ZGUwNy1iODg3LTQxNmUtODY4ZS03YTgxMGYxNjQzMDIJc2JlcmJhbmsJ"
        "cGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTM6"
        "NTc6MjcJOWFhNzEyYTctNDZiOC00ZmY5LThmNjQtMDVkOTZkNDU0NzNjCTEwNmYyOWVhLTRjZDUtNDJmMy05OWQ5LTQ2YzFiOGUw"
        "ZjMyMglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAxIDEwOjU1OjMzCTZjMDBiOWE3LWVhZGQtNGYxYS05MzA1LTlmYmY4Zjkw"
        "Mjg5NAkxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjIJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3"
        "IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDIgMDk6Mzg6NDMJOWVjYzkxYzQtYTU4MC00Y2Jm"
        "LTgyM2UtNTE5MzU0ZTc5YTYwCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAyIDA2OjM3OjQxCTk1YTY2M2RjLTFmMDctNDEy"
        "Yy1iNjZjLTVhNTQ1Y2EyZDRhYQlkYTk5YTQzNi0xZGM1LTRhODYtOTUxZC1lODczN2Y5MWI4ZmQJCQlJCTIwMjYtMDQtMDcgMTA6"
        "NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMSAxNDoyNDowMwk5ZmE1NjhlYS02Njk1LTRmYmUtOWRl"
        "MC1iZTU5OTM4Mzk0YWEJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDEgMTE6MjI6MDEJZjhkODI1ODktMmY0ZS00ZDg1LWEy"
        "MDgtMjczMDRmZWZjMDcwCWVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMAkJCUkJMjAyNi0wNC0wNyAxMDo0NDow"
        "Mi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAzIDE5OjUzOjMzCWEwZjE4YTc5LTYwODItNGUxMC1iNDcwLWE3"
        "YzgyNjc4N2JkNwk0NjQ4MzdkNi01YzRmLTQ4MWQtYmUwNy00YWI5OTkzMTdiZGYJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0w"
        "MyAxNjo1Mjo1NAkyYTQ0ZjkyNC0xOWNmLTQ2ZGEtOGQ1MC00ZjZjYTI3MGEwZDMJNDY0ODM3ZDYtNWM0Zi00ODFkLWJlMDctNGFi"
        "OTk5MzE3YmRmCXNiZXJiYW5rCQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0w"
        "NC0wMyAxNjoyNDozNwlhMzIyMjRmYS1hOTU0LTRlYjktOWY3OC0wNmRjNzFkODU3MDYJYjdjYTBkNTItMThmOC00NzcxLTliMWQt"
        "NjAyNWU2ZjAzYTI5CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTM6MjM6NTIJYWIzYTdhN2UtYWQ0Yy00MTBmLTkxNjct"
        "Zjg3NDBlMjUzOWRlCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOQlzYmVyYmFuawkJSQkyMDI2LTA0LTA3IDEw"
        "OjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTk6NTM6MzMJYTY0ZTBhN2MtNWExZS00ZTAzLWE5"
        "MzYtNjBhMDk0ZGViZjNjCQlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAzIDE2OjUyOjUyCWRhNDE1ZmJhLWQ4OTQtNDhlYi1h"
        "ZWY1LThlYTdkOGY4NmQ2YQk0NjQ4MzdkNi01YzRmLTQ4MWQtYmUwNy00YWI5OTkzMTdiZGYJCQlJCTIwMjYtMDQtMDcgMTA6NDQ6"
        "MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMiAxMzo0NDo1NwlhYjk3MmMyYy04ZDE2LTRhY2YtOWU2MC1m"
        "ZmVjOWJjZmQyOTYJYjdjYTBkNTItMThmOC00NzcxLTliMWQtNjAyNWU2ZjAzYTI5CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQt"
        "MDIgMTA6NDQ6NDYJMzA0M2M1OGUtZTgzNS00OGMxLWI5ZDMtMGVkZWMxMzhmODMyCWI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYw"
        "MjVlNmYwM2EyOQlzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6"
        "MTc6MTUJMjAyNi0wNC0wMyAyMDoxMToyNgliYzg5YjU5MS1iMDdmLTRkZDAtYTgzOC1mMTQxZjNiNjRkMzEJZWMwNzhmNWYtNTI5"
        "My00ZjVjLTlhYzAtZjhlMTYyMTJlOTYxCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MTIJMmE0NGY5MjQtMTlj"
        "Zi00NmRhLThkNTAtNGY2Y2EyNzBhMGQzCWVjMDc4ZjVmLTUyOTMtNGY1Yy05YWMwLWY4ZTE2MjEyZTk2MQlzYmVyYmFuawkJSQky"
        "MDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDEgMTI6Mjk6MjgJY2UwNDI0NWIt"
        "ODZhYS00M2NiLTg5Y2ItOTg3OTUxZTMwNjRjCWVhNjg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZQlDYXRhbG9nSXRl"
        "bU9wZW5lZAkyMDI2LTA0LTAxIDA5OjI4OjQ2CWIzMWUwM2I0LTZkZTYtNDMzYy1hNzg2LWE5ODk0NjVkYTQyZAllYTY4OThhOS02"
        "MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWUJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDEx"
        "MgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIwMjYtMDQtMDMgMTE6MjM6MzYJZDljYjExZjAtZmE1OC00ZmMzLTg1OTMtMzllZmNlYjZj"
        "MzllCWNhNjBlMzIzLTkwNWMtNGQ5Ny1iNGQ1LWRlYmU2NWUzMTk4ZAlDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTAzIDA4OjIx"
        "OjAyCWRiNGNmYmRjLWMyMTYtNGZhNy05NmI2LTZkYmU0NTNjZjA3YwljYTYwZTMyMy05MDVjLTRkOTctYjRkNS1kZWJlNjVlMzE5"
        "OGQJc2JlcmJhbmsJcGFvc2JlcmJhbmsJSQkyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMgoyMDI2LTA0LTA3IDEwOjE3OjE1CTIw"
        "MjYtMDQtMDYgMTY6NDA6NDIJZGM4MWQ3ZWEtMWNjNi00NDk1LThhNzYtMDA2MWU2YjdjYTY4CTBiYzMzYmVhLTA4N2ItNDU2ZC04"
        "YmVmLTY5YjkzZTljNDk0NglDYXRhbG9nSXRlbU9wZW5lZAkyMDI2LTA0LTA2IDEzOjQwOjIxCWZkZDdhMGUwLTkyN2EtNDQ4OS04"
        "OWFkLTcxNmFlYzhiZjc0YwkwYmMzM2JlYS0wODdiLTQ1NmQtOGJlZi02OWI5M2U5YzQ5NDYJc2JlcmJhbmsJCUkJMjAyNi0wNC0w"
        "NyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTAzIDE5OjU0OjIxCWU2MDliYWMyLWIyMzctNDhh"
        "Yy05NDY3LWVmN2U2NmJiZTRiMAk5Zjg2ZWY2Yy02OGQ1LTQ3MDEtOTMyOC1iNGVlMDQ3NTBhNzAJQ2F0YWxvZ0l0ZW1PcGVuZWQJ"
        "MjAyNi0wNC0wMyAxNjo1MzozNgkyYTQ0ZjkyNC0xOWNmLTQ2ZGEtOGQ1MC00ZjZjYTI3MGEwZDMJOWY4NmVmNmMtNjhkNS00NzAx"
        "LTkzMjgtYjRlZTA0NzUwYTcwCXNiZXJiYW5rCQlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6"
        "MTUJMjAyNi0wNC0wNiAxNjo0NjozMwllNmRiNWZjZS1hZTUxLTQ4MGQtYWJlNS03ODIwMmRkOWJmZGUJMGJjMzNiZWEtMDg3Yi00"
        "NTZkLThiZWYtNjliOTNlOWM0OTQ2CUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDYgMTM6NDU6NDgJMmFkZGFlNTgtZDRkNi00"
        "ZmM5LWEzMDYtMmI5OTMzOGFlMTI3CTBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0NglzYmVyYmFuawlwYW9zYmVy"
        "YmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAxNjowOTo0NQll"
        "YzBlMmRlMS1hZDY5LTQ2ODAtYjMxMC1jYjYxYzk1NDBlOWEJZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlCUNh"
        "dGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTM6MDc6MjkJNzVjMTE1MWMtNDJhMi00OWM0LTkwZjAtZmEwMDhlMWQ3OWUwCWVh"
        "Njg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZQlzYmVyYmFuawlwYW9zYmVyYmFuawlJCTIwMjYtMDQtMDcgMTA6NDQ6"
        "MDIuMDAwMTEyCjIwMjYtMDQtMDcgMTA6MTc6MTUJMjAyNi0wNC0wMyAyMDoxMjowMQllZDMxOTNjMy0wZTdlLTQ2YTQtOWQ1Zi1m"
        "NTJhZDVjN2Q5OTAJCUNhdGFsb2dJdGVtT3BlbmVkCTIwMjYtMDQtMDMgMTc6MTA6MjkJNTYwOWNiYWQtYTI0My00NGUyLWI2MDIt"
        "NjdjNDc3NGI2ZjgwCTVkMzhkMWM2LTM5MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOQkJCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4w"
        "MDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNQkyMDI2LTA0LTA2IDEyOjExOjE1CWYxNGYzNmU0LTBlODktNDQ5NS05YWVhLWI5OTYy"
        "MGViYWNhYgkyMjhkNDYwNC1hZDJjLTRmNjQtOGYzZS00NzE4YjZlNjA4NWYJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wNiAw"
        "OToxMDowNwk2YjQzMjIwNi1mMzA4LTQwNWYtOTU2Yi1jZjIyNTgwNjk3YmUJMjI4ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2"
        "ZTYwODVmCXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzox"
        "NgkyMDI2LTA0LTA2IDEyOjExOjE1CWYxNGYzNmU0LTBlODktNDQ5NS05YWVhLWI5OTYyMGViYWNhYgkyMjhkNDYwNC1hZDJjLTRm"
        "NjQtOGYzZS00NzE4YjZlNjA4NWYJQ2F0YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wNiAwOToxMDowNwk2YjQzMjIwNi1mMzA4LTQw"
        "NWYtOTU2Yi1jZjIyNTgwNjk3YmUJMjI4ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2ZTYwODVmCXNiZXJiYW5rCXBhb3NiZXJi"
        "YW5rCUkJMjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIKMjAyNi0wNC0wNyAxMDoxNzoxNwkyMDI2LTA0LTA2IDEyOjExOjE1CWYx"
        "NGYzNmU0LTBlODktNDQ5NS05YWVhLWI5OTYyMGViYWNhYgkyMjhkNDYwNC1hZDJjLTRmNjQtOGYzZS00NzE4YjZlNjA4NWYJQ2F0"
        "YWxvZ0l0ZW1PcGVuZWQJMjAyNi0wNC0wNiAwOToxMDowNwk2YjQzMjIwNi1mMzA4LTQwNWYtOTU2Yi1jZjIyNTgwNjk3YmUJMjI4"
        "ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2ZTYwODVmCXNiZXJiYW5rCXBhb3NiZXJiYW5rCUkJMjAyNi0wNC0wNyAxMDo0NDow"
        "Mi4wMDAxMTIK",
        38,
    ),
]


@dag(
    doc_md=__doc__,
    default_args={"owner": "DataLab (CI02420667)", "retries": 0},
    owner_links={"DataLab (CI02420667)": "https://confluence.sberbank.ru/display/HRTECH/DataLab"},
    start_date=pendulum.datetime(2025, 8, 7, tz=pendulum.UTC),
    tags=["DataLab", "tools", "test"],
    catchup=False,
    is_paused_upon_creation=True,
    max_active_runs=1,
    schedule_interval=None,
    params={
        "prefix": Param("hrplatform_datalab", type="string", description="Префикс имени файла"),
        "table_name": Param("learning__lc_items_opened", type="string", description="Таблица в формате schema__table"),
        "s3_prefix": Param(
            "from/KAP802/hrpl_lm_er/hrplatform_datalab",
            type="string",
            description="Папка в бакете (без слэша в конце)",
        ),
        "bucket": Param("edpetl-test", type="string", description="S3 бакет"),
        "conn_id": Param("s3-archive", type="string", description="Airflow S3 connection ID"),
    },
)
def tools_test_package():

    @task(task_id="upload")
    def upload(**context):
        p = context["params"]
        prefix = p["prefix"]
        full_table = p["table_name"]
        schema, _, table_name = full_table.partition("__")
        s3_prefix = p["s3_prefix"].rstrip("/")
        bucket = p["bucket"]
        total = len(_PARTS)

        base_ts = pendulum.now("UTC")
        hook = S3Hook(aws_conn_id=p["conn_id"])
        meta_bytes = base64.b64decode(_META)
        uploaded = []

        for i, (csv_b64, rows) in enumerate(_PARTS):
            part = i + 1
            csv_bytes = base64.b64decode(csv_b64)

            inner_ts = base_ts.add(seconds=i * 2).format("YYYYMMDDHHmmss")
            tkt_ts   = base_ts.add(seconds=i * 2 + 1).format("YYYYMMDDHHmmss")
            outer_ts = base_ts.add(seconds=i * 2 + 2).format("YYYYMMDDHHmmss")

            csv_name  = f"{schema}__{table_name}__{inner_ts}__{part}_{total}_{rows}.csv"
            meta_name = f"{schema}__{table_name}__{inner_ts}__{part}_{total}_{rows}.meta"
            tkt_name  = f"{prefix}__{tkt_ts}.tkt"
            tkt_bytes = f"{csv_name};{rows}".encode()
            zip_name  = f"{prefix}__{outer_ts}__{table_name}__{part}_{total}_{rows}.csv.zip"

            buf = BytesIO()
            with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
                zf.writestr(meta_name, meta_bytes)
                zf.writestr(tkt_name, tkt_bytes)
                zf.writestr(csv_name, csv_bytes)
            buf.seek(0)

            s3_key = f"{s3_prefix}/{zip_name}"
            hook.load_bytes(buf.getvalue(), key=s3_key, bucket_name=bucket, replace=True)
            uploaded.append(s3_key)

        for key in uploaded:
            import logging
            logging.getLogger("airflow.task").info("✅ uploaded: %s", key)

        return uploaded


    upload()


tools_test_package()
