"""### 📦 Тестовый пакет для единого репликатора / TFS

Загружает тестовые ZIP-пакеты в S3 с актуальными таймштампами.
По умолчанию используются встроенные тестовые данные (3 части, 36/37/38 строк).
Содержимое и схему можно переопределить через параметры `parts` и `meta`.

| Параметр       | Описание                                                              |
|----------------|-----------------------------------------------------------------------|
| `prefix`       | Префикс имени файла *(default: hrplatform_datalab)*                   |
| `table_name`   | Таблица в формате schema__table *(default: learning__lc_items_opened)*|
| `s3_prefix`    | Папка в бакете *(default: from/KAP802/...)*                           |
| `bucket`       | S3 бакет *(default: edpetl-test)*                                     |
| `conn_id`      | Airflow S3 connection *(default: s3-archive)*                         |
| `meta`         | JSON-схема для .meta файла                                            |
| `parts`        | Список строк CSV (повтор заголовка = новая часть)                     |
"""

from __future__ import annotations
import base64
import json
import os
import zipfile
from io import BytesIO

import pendulum
from airflow.decorators import dag, task
from airflow.models import Param
from airflow.providers.amazon.aws.hooks.s3 import S3Hook


_META = '{"schema_name": "learning", "table_name": "lc_items_opened", "strategy": "FULL_UK", "PK": [], "UK": ["person_uuid", "item_id"], "params": {"separation": "\\t", "escapesymbol": "\\""}, "columns": [{"column_name": "export_time", "source_type": "TIMESTAMP", "length": null, "notnull": false, "precision": null, "scale": null, "description": "Дата выгрузки"}, {"column_name": "insert_time", "source_type": "TIMESTAMP", "length": null, "notnull": false, "precision": null, "scale": null, "description": "Дата вставки"}, {"column_name": "header_id", "source_type": "STRING", "length": null, "notnull": false, "precision": 38, "scale": 10, "description": "Уникальный идентификатор ивента"}, {"column_name": "header_person_id", "source_type": "STRING", "length": 4096, "notnull": false, "precision": null, "scale": null, "description": "ID сотрудника, изучающего материал"}, {"column_name": "header_event_type", "source_type": "STRING", "length": 4096, "notnull": false, "precision": null, "scale": null, "description": "Тип ивента"}, {"column_name": "header_created_dt", "source_type": "DATE", "length": 4096, "notnull": false, "precision": null, "scale": null, "description": "Дата генерации ивента"}, {"column_name": "item_id", "source_type": "INT", "length": 25, "notnull": true, "precision": null, "scale": null, "description": "ID материала"}, {"column_name": "person_uuid", "source_type": "INT", "length": 25, "notnull": true, "precision": null, "scale": null, "description": "ID сотрудника, изучающего материал"}, {"column_name": "tenant", "source_type": "STRING", "length": 4096, "notnull": false, "precision": null, "scale": null, "description": "тенант"}, {"column_name": "company", "source_type": "STRING", "length": 4096, "notnull": false, "precision": null, "scale": null, "description": "компания"}, {"column_name": "ctl_action", "source_type": "VARCHAR", "length": 10, "notnull": false, "precision": null, "scale": null, "description": null}, {"column_name": "ctl_validfrom", "source_type": "TIMESTAMP", "length": null, "notnull": false, "precision": null, "scale": null, "description": null}]}'

# base64(json список всех строк CSV, повтор заголовка = новая часть)
_PARTS = "".join([
    "WyJleHBvcnRfdGltZVx0aW5zZXJ0X3RpbWVcdGhlYWRlcl9pZFx0aGVhZGVyX3BlcnNvbl9pZFx0aGVhZGVyX2V2ZW50X3R5cGVc",
    "dGhlYWRlcl9jcmVhdGVkX2R0XHRpdGVtX2lkXHRwZXJzb25fdXVpZFx0dGVuYW50XHRjb21wYW55XHRjdGxfYWN0aW9uXHRjdGxf",
    "dmFsaWRmcm9tIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTI6NDg6NDNcdDA5ZGI5MThiLWZkODAtNGFmYS1h",
    "NzFiLTY2ZmQzNTRiNTIxMlx0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlXHRDYXRhbG9nSXRlbU9wZW5lZFx0",
    "MjAyNi0wNC0wMSAwOTo0Nzo0M1x0MWQ1MWJlNTAtZGU5ZS00MTJjLTllYjgtMjA4NWZiYmZkODQwXHRlYTY4OThhOS02MzAyLTQw",
    "NmUtODlmNy05NzlmYTQyMzdhZWVcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIi",
    "LCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMyAyMDoxMTozMFx0MGNiODU0ODEtNjgzZi00N2E1LWJjY2EtOWZiMjFi",
    "YjdhNmYzXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAzIDE3OjEwOjEwXHRkYTQxNWZiYS1kODk0LTQ4ZWItYWVmNS04",
    "ZWE3ZDhmODZkNmFcdGVjMDc4ZjVmLTUyOTMtNGY1Yy05YWMwLWY4ZTE2MjEyZTk2MVx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6",
    "MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTM6NTk6MThcdDEyOWIyZTYzLTYwZTAtNDkwYS1h",
    "N2IyLWU5NjI3OGRhNmNlZlx0MTA2ZjI5ZWEtNGNkNS00MmYzLTk5ZDktNDZjMWI4ZTBmMzIyXHRDYXRhbG9nSXRlbU9wZW5lZFx0",
    "MjAyNi0wNC0wMSAxMDo1ODowOVx0NzVjMTE1MWMtNDJhMi00OWM0LTkwZjAtZmEwMDhlMWQ3OWUwXHQxMDZmMjllYS00Y2Q1LTQy",
    "ZjMtOTlkOS00NmMxYjhlMGYzMjJcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIi",
    "LCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMSAxNDoyOTowOFx0MTI5YjczODUtODkxMS00NDczLWE3MzEtMjRkYmFl",
    "NGZmNDYxXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDExOjI3OjMxXHRmOGQ4MjU4OS0yZjRlLTRkODUtYTIwOC0y",
    "NzMwNGZlZmMwNzBcdGVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMFx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6",
    "MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIgMTA6MTY6MjNcdDI1OTlkZWMwLWMyNzUtNDZlNS1h",
    "MTQ5LTBkZjQwZmY3ZTBhMFx0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAwNzoxNToxNVx0MjI0OTJhOTMtNzk3Yi00",
    "NGJiLTlmYmMtZTM5ZTM4Yjk2NDgwXHRhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWRcdFx0XHRJXHQyMDI2LTA0",
    "LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDE2OjQ4OjA5XHQyYzIwNzFiNi1h",
    "MTMxLTRmOGMtYjY4Yi0yNTljNGNlMmRkMTZcdDY4MDg4MGU1LWQ5NjgtNGU1Yi04NjQwLTVhNDA0OGExZGU3NFx0Q2F0YWxvZ0l0",
    "ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMTM6Mzc6NDNcdGU1NDE2ZDczLTZjZmMtNDk0NS1iOTAxLWZhNDZiZWI4YTkxMFx0NjgwODgw",
    "ZTUtZDk2OC00ZTViLTg2NDAtNWE0MDQ4YTFkZTc0XHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6",
    "MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTQ6MzI6MDdcdDJlY2IwMzk2LTYzMjctNDRiYi05",
    "YzJmLTM4ZDc3NWVmNTQyNVx0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAxMTozMDo0N1x0ZjhkODI1ODktMmY0ZS00",
    "ZDg1LWEyMDgtMjczMDRmZWZjMDcwXHRlZjA4YjZmMi0zNDkyLTRmMGItOTM2MC1hMmRiZjM4MmI4MTBcdFx0XHRJXHQyMDI2LTA0",
    "LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDA5OjE2OjQ4XHQzMTRlNTEyNS1h",
    "ZjIwLTQ1ZTktOTdhZS1lMTI0NDBlZTZhNGNcdDMzMzk1NTJiLTAxMmItNDMwMi1iMzMxLTEyOTIyOWM1OGVlZVx0Q2F0YWxvZ0l0",
    "ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMDY6MTY6MDRcdGU3ZThhNjRiLTJhNWEtNDkxYS1iMzBlLTE1OTc2YTJmMzkwMFx0MzMzOTU1",
    "MmItMDEyYi00MzAyLWIzMzEtMTI5MjI5YzU4ZWVlXHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6",
    "MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIgMTI6NTQ6NTRcdDM1NjBiOGIxLTc4MzMtNDZiNC1i",
    "YTYzLTBiYmIyODgxNDU4M1x0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAwOTo1NDoyM1x0OTVhNjYzZGMtMWYwNy00",
    "MTJjLWI2NmMtNWE1NDVjYTJkNGFhXHRhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWRcdFx0XHRJXHQyMDI2LTA0",
    "LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDE3OjE3OjIyXHQ1NGRlNDYzNy1k",
    "ZDM3LTQ5ODctOTQ3ZS03OGRkYzBhOGY0NDhcdDBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0Nlx0Q2F0YWxvZ0l0",
    "ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMTQ6MTA6MDRcdGYwZDg1Yzc3LTFlNjctNDdhYy1hNDAyLTE0OTdiOTYyNmY4Ylx0MGJjMzNi",
    "ZWEtMDg3Yi00NTZkLThiZWYtNjliOTNlOWM0OTQ2XHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6",
    "MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMgMTk6NTM6MzNcdDU3YzY4ZDdjLTY4NmUtNDRkMy1i",
    "YzdiLWQ2ODZlNzQ5MzhkOFx0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAxNjo1MjowOFx0NTYwOWNiYWQtYTI0My00",
    "NGUyLWI2MDItNjdjNDc3NGI2ZjgwXHQ5Zjg2ZWY2Yy02OGQ1LTQ3MDEtOTMyOC1iNGVlMDQ3NTBhNzBcdFx0XHRJXHQyMDI2LTA0",
    "LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAxIDEzOjU5OjE0XHQ1ZWNkMzZjZS01",
    "YjIwLTQzMmQtOTg1Ny1lZWI3YTI0NzllNWNcdGVhNjg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZVx0Q2F0YWxvZ0l0",
    "ZW1PcGVuZWRcdDIwMjYtMDQtMDEgMTA6NTY6MzRcdDZjMDBiOWE3LWVhZGQtNGYxYS05MzA1LTlmYmY4ZjkwMjg5NFx0ZWE2ODk4",
    "YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlXHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6",
    "MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTQ6Mjc6MDZcdDYzZTFkYTdmLTNiZGUtNDFhMS05",
    "NzFmLTEyY2ZiYjBlMTFmM1x0ZWYwOGI2ZjItMzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwXHRDYXRhbG9nSXRlbU9wZW5lZFx0",
    "MjAyNi0wNC0wMSAxMToyNTo0OVx0OGY0NTQ1ZWEtYzcxYS00ZmU1LTk3M2YtMzI5NWEwZWY5NTc5XHRlZjA4YjZmMi0zNDkyLTRm",
    "MGItOTM2MC1hMmRiZjM4MmI4MTBcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIi",
    "LCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMSAxNDozMzozNVx0NmVjY2ZiMjgtZDdjYi00NDE3LTgzOTQtYTMyM2Rj",
    "YmM0M2FlXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDExOjMyOjAwXHRmOGQ4MjU4OS0yZjRlLTRkODUtYTIwOC0y",
    "NzMwNGZlZmMwNzBcdGVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMFx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6",
    "MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMgMTY6MDk6MTRcdDdhYTUxZDNlLTgxYTctNDNlNS04",
    "MTE2LTNjMDNlNTk5ZjNiMVx0NWI3ZTBlYTYtYzUwZi00NjE3LWFkNGMtNGMwZjAyNjAyMzA4XHRDYXRhbG9nSXRlbU9wZW5lZFx0",
    "MjAyNi0wNC0wMyAxMzowNzoxNVx0NzVjMTE1MWMtNDJhMi00OWM0LTkwZjAtZmEwMDhlMWQ3OWUwXHQ1YjdlMGVhNi1jNTBmLTQ2",
    "MTctYWQ0Yy00YzBmMDI2MDIzMDhcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIi",
    "LCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wNiAxODoyNjoxNVx0N2I4ZmNhMzctMGY2OS00ZWZhLTlhYTctYWQzNDIw",
    "MjRhOGNhXHRiN2NhMGQ1Mi0xOGY4LTQ3NzEtOWIxZC02MDI1ZTZmMDNhMjlcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTA2",
    "IDE1OjI1OjM3XHQzZDRhMWUwOS04ZDEwLTRhZjktYjY4ZC0yYjViZmQ4YjQwZDBcdGI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYw",
    "MjVlNmYwM2EyOVx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0",
    "LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDEzOjAzOjU1XHQ4MWMzZmM3NS04NzZhLTRmYmMtOGY0Zi0yY2E1YjJmYTI4MGRcdDMz",
    "Mzk1NTJiLTAxMmItNDMwMi1iMzMxLTEyOTIyOWM1OGVlZVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMTA6MDM6MDZc",
    "dGVlYjU0NjE2LWJmYzItNDdiOC05YmYyLWRjMDczY2VjNjc4NVx0MzMzOTU1MmItMDEyYi00MzAyLWIzMzEtMTI5MjI5YzU4ZWVl",
    "XHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6",
    "MTVcdDIwMjYtMDQtMDIgMDk6NTk6MDVcdDg0Y2NlNDcxLTk0NzUtNGU5Zi1iNzc5LWJiOTIxY2QwMDEyZVx0XHRDYXRhbG9nSXRl",
    "bU9wZW5lZFx0MjAyNi0wNC0wMiAwNjo1ODowM1x0OTVhNjYzZGMtMWYwNy00MTJjLWI2NmMtNWE1NDVjYTJkNGFhXHRhN2NlYTIw",
    "ZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWRcdFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0",
    "LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDIwOjExOjQ4XHQ5NWNhNGVjZC1lNzVlLTRiNjMtYmY1YS02MTFiN2Y1YzY1NDlcdDVk",
    "MzhkMWM2LTM5MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTc6MTA6MzBc",
    "dDJhNDRmOTI0LTE5Y2YtNDZkYS04ZDUwLTRmNmNhMjcwYTBkM1x0NWQzOGQxYzYtMzkxNy00MDRmLTg3YzktN2U4YTk2NDJkNmY5",
    "XHRzYmVyYmFua1x0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0",
    "LTAxIDE0OjM0OjAxXHQ5Njk5MjZkMy1iZGZjLTQzOTgtYTJkNC1hMWNlNzE3MTY2YzdcdGM1MDVkZTA3LWI4ODctNDE2ZS04Njhl",
    "LTdhODEwZjE2NDMwMlx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDEgMTE6MzM6MDlcdDRkNDg5ZDhjLWJjZjMtNDJkOS05",
    "YTFhLTBlMzUwMTI0MDc4YVx0YzUwNWRlMDctYjg4Ny00MTZlLTg2OGUtN2E4MTBmMTY0MzAyXHRzYmVyYmFua1x0cGFvc2JlcmJh",
    "bmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTM6NTc6",
    "MjdcdDlhYTcxMmE3LTQ2YjgtNGZmOS04ZjY0LTA1ZDk2ZDQ1NDczY1x0MTA2ZjI5ZWEtNGNkNS00MmYzLTk5ZDktNDZjMWI4ZTBm",
    "MzIyXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAxMDo1NTozM1x0NmMwMGI5YTctZWFkZC00ZjFhLTkzMDUtOWZiZjhm",
    "OTAyODk0XHQxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjJcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAy",
    "Ni0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMiAwOTozODo0M1x0OWVjYzkx",
    "YzQtYTU4MC00Y2JmLTgyM2UtNTE5MzU0ZTc5YTYwXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAyIDA2OjM3OjQxXHQ5",
    "NWE2NjNkYy0xZjA3LTQxMmMtYjY2Yy01YTU0NWNhMmQ0YWFcdGRhOTlhNDM2LTFkYzUtNGE4Ni05NTFkLWU4NzM3ZjkxYjhmZFx0",
    "XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTQ6MjQ6",
    "MDNcdDlmYTU2OGVhLTY2OTUtNGZiZS05ZGUwLWJlNTk5MzgzOTRhYVx0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAx",
    "MToyMjowMVx0ZjhkODI1ODktMmY0ZS00ZDg1LWEyMDgtMjczMDRmZWZjMDcwXHRlZjA4YjZmMi0zNDkyLTRmMGItOTM2MC1hMmRi",
    "ZjM4MmI4MTBcdFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0",
    "LTAzIDE5OjUzOjMzXHRhMGYxOGE3OS02MDgyLTRlMTAtYjQ3MC1hN2M4MjY3ODdiZDdcdDQ2NDgzN2Q2LTVjNGYtNDgxZC1iZTA3",
    "LTRhYjk5OTMxN2JkZlx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTY6NTI6NTRcdDJhNDRmOTI0LTE5Y2YtNDZkYS04",
    "ZDUwLTRmNmNhMjcwYTBkM1x0NDY0ODM3ZDYtNWM0Zi00ODFkLWJlMDctNGFiOTk5MzE3YmRmXHRzYmVyYmFua1x0XHRJXHQyMDI2",
    "LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDE2OjI0OjM3XHRhMzIyMjRm",
    "YS1hOTU0LTRlYjktOWY3OC0wNmRjNzFkODU3MDZcdGI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOVx0Q2F0YWxv",
    "Z0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTM6MjM6NTJcdGFiM2E3YTdlLWFkNGMtNDEwZi05MTY3LWY4NzQwZTI1MzlkZVx0Yjdj",
    "YTBkNTItMThmOC00NzcxLTliMWQtNjAyNWU2ZjAzYTI5XHRzYmVyYmFua1x0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDEx",
    "MiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDE5OjUzOjMzXHRhNjRlMGE3Yy01YTFlLTRlMDMtYTkzNi02MGEw",
    "OTRkZWJmM2NcdFx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTY6NTI6NTJcdGRhNDE1ZmJhLWQ4OTQtNDhlYi1hZWY1",
    "LThlYTdkOGY4NmQ2YVx0NDY0ODM3ZDYtNWM0Zi00ODFkLWJlMDctNGFiOTk5MzE3YmRmXHRcdFx0SVx0MjAyNi0wNC0wNyAxMDo0",
    "NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMiAxMzo0NDo1N1x0YWI5NzJjMmMtOGQxNi00YWNm",
    "LTllNjAtZmZlYzliY2ZkMjk2XHRiN2NhMGQ1Mi0xOGY4LTQ3NzEtOWIxZC02MDI1ZTZmMDNhMjlcdENhdGFsb2dJdGVtT3BlbmVk",
    "XHQyMDI2LTA0LTAyIDEwOjQ0OjQ2XHQzMDQzYzU4ZS1lODM1LTQ4YzEtYjlkMy0wZWRlYzEzOGY4MzJcdGI3Y2EwZDUyLTE4Zjgt",
    "NDc3MS05YjFkLTYwMjVlNmYwM2EyOVx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDEx",
    "MiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDIwOjExOjI2XHRiYzg5YjU5MS1iMDdmLTRkZDAtYTgzOC1mMTQx",
    "ZjNiNjRkMzFcdGVjMDc4ZjVmLTUyOTMtNGY1Yy05YWMwLWY4ZTE2MjEyZTk2MVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQt",
    "MDMgMTc6MTA6MTJcdDJhNDRmOTI0LTE5Y2YtNDZkYS04ZDUwLTRmNmNhMjcwYTBkM1x0ZWMwNzhmNWYtNTI5My00ZjVjLTlhYzAt",
    "ZjhlMTYyMTJlOTYxXHRzYmVyYmFua1x0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3",
    "OjE1XHQyMDI2LTA0LTAxIDEyOjI5OjI4XHRjZTA0MjQ1Yi04NmFhLTQzY2ItODljYi05ODc5NTFlMzA2NGNcdGVhNjg5OGE5LTYz",
    "MDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDEgMDk6Mjg6NDZcdGIzMWUwM2I0",
    "LTZkZTYtNDMzYy1hNzg2LWE5ODk0NjVkYTQyZFx0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlXHRzYmVyYmFu",
    "a1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYt",
    "MDQtMDMgMTE6MjM6MzZcdGQ5Y2IxMWYwLWZhNTgtNGZjMy04NTkzLTM5ZWZjZWI2YzM5ZVx0Y2E2MGUzMjMtOTA1Yy00ZDk3LWI0",
    "ZDUtZGViZTY1ZTMxOThkXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAwODoyMTowMlx0ZGI0Y2ZiZGMtYzIxNi00ZmE3",
    "LTk2YjYtNmRiZTQ1M2NmMDdjXHRjYTYwZTMyMy05MDVjLTRkOTctYjRkNS1kZWJlNjVlMzE5OGRcdHNiZXJiYW5rXHRwYW9zYmVy",
    "YmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wNiAxNjo0",
    "MDo0Mlx0ZGM4MWQ3ZWEtMWNjNi00NDk1LThhNzYtMDA2MWU2YjdjYTY4XHQwYmMzM2JlYS0wODdiLTQ1NmQtOGJlZi02OWI5M2U5",
    "YzQ5NDZcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTA2IDEzOjQwOjIxXHRmZGQ3YTBlMC05MjdhLTQ0ODktODlhZC03MTZh",
    "ZWM4YmY3NGNcdDBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0Nlx0c2JlcmJhbmtcdFx0SVx0MjAyNi0wNC0wNyAx",
    "MDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMyAxOTo1NDoyMVx0ZTYwOWJhYzItYjIzNy00",
    "OGFjLTk0NjctZWY3ZTY2YmJlNGIwXHQ5Zjg2ZWY2Yy02OGQ1LTQ3MDEtOTMyOC1iNGVlMDQ3NTBhNzBcdENhdGFsb2dJdGVtT3Bl",
    "bmVkXHQyMDI2LTA0LTAzIDE2OjUzOjM2XHQyYTQ0ZjkyNC0xOWNmLTQ2ZGEtOGQ1MC00ZjZjYTI3MGEwZDNcdDlmODZlZjZjLTY4",
    "ZDUtNDcwMS05MzI4LWI0ZWUwNDc1MGE3MFx0c2JlcmJhbmtcdFx0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAy",
    "Ni0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wNiAxNjo0NjozM1x0ZTZkYjVmY2UtYWU1MS00ODBkLWFiZTUtNzgyMDJkZDliZmRl",
    "XHQwYmMzM2JlYS0wODdiLTQ1NmQtOGJlZi02OWI5M2U5YzQ5NDZcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTA2IDEzOjQ1",
    "OjQ4XHQyYWRkYWU1OC1kNGQ2LTRmYzktYTMwNi0yYjk5MzM4YWUxMjdcdDBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTlj",
    "NDk0Nlx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEw",
    "OjE3OjE1XHQyMDI2LTA0LTAzIDE2OjA5OjQ1XHRlYzBlMmRlMS1hZDY5LTQ2ODAtYjMxMC1jYjYxYzk1NDBlOWFcdGVhNjg5OGE5",
    "LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTM6MDc6MjlcdDc1YzEx",
    "NTFjLTQyYTItNDljNC05MGYwLWZhMDA4ZTFkNzllMFx0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlXHRzYmVy",
    "YmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIw",
    "MjYtMDQtMDMgMjA6MTI6MDFcdGVkMzE5M2MzLTBlN2UtNDZhNC05ZDVmLWY1MmFkNWM3ZDk5MFx0XHRDYXRhbG9nSXRlbU9wZW5l",
    "ZFx0MjAyNi0wNC0wMyAxNzoxMDoyOVx0NTYwOWNiYWQtYTI0My00NGUyLWI2MDItNjdjNDc3NGI2ZjgwXHQ1ZDM4ZDFjNi0zOTE3",
    "LTQwNGYtODdjOS03ZThhOTY0MmQ2ZjlcdFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEw",
    "OjE3OjE1XHQyMDI2LTA0LTA2IDEyOjExOjE1XHRmMTRmMzZlNC0wZTg5LTQ0OTUtOWFlYS1iOTk2MjBlYmFjYWJcdDIyOGQ0NjA0",
    "LWFkMmMtNGY2NC04ZjNlLTQ3MThiNmU2MDg1Zlx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDYgMDk6MTA6MDdcdDZiNDMy",
    "MjA2LWYzMDgtNDA1Zi05NTZiLWNmMjI1ODA2OTdiZVx0MjI4ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2ZTYwODVmXHRzYmVy",
    "YmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgImV4cG9ydF90aW1lXHRpbnNlcnRfdGlt",
    "ZVx0aGVhZGVyX2lkXHRoZWFkZXJfcGVyc29uX2lkXHRoZWFkZXJfZXZlbnRfdHlwZVx0aGVhZGVyX2NyZWF0ZWRfZHRcdGl0ZW1f",
    "aWRcdHBlcnNvbl91dWlkXHR0ZW5hbnRcdGNvbXBhbnlcdGN0bF9hY3Rpb25cdGN0bF92YWxpZGZyb20iLCAiMjAyNi0wNC0wNyAx",
    "MDoxNzoxNVx0MjAyNi0wNC0wMSAxMjo0ODo0M1x0MDlkYjkxOGItZmQ4MC00YWZhLWE3MWItNjZmZDM1NGI1MjEyXHRlYTY4OThh",
    "OS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWVcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDA5OjQ3OjQzXHQxZDUx",
    "YmU1MC1kZTllLTQxMmMtOWViOC0yMDg1ZmJiZmQ4NDBcdGVhNjg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZVx0c2Jl",
    "cmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQy",
    "MDI2LTA0LTAzIDIwOjExOjMwXHQwY2I4NTQ4MS02ODNmLTQ3YTUtYmNjYS05ZmIyMWJiN2E2ZjNcdFx0Q2F0YWxvZ0l0ZW1PcGVu",
    "ZWRcdDIwMjYtMDQtMDMgMTc6MTA6MTBcdGRhNDE1ZmJhLWQ4OTQtNDhlYi1hZWY1LThlYTdkOGY4NmQ2YVx0ZWMwNzhmNWYtNTI5",
    "My00ZjVjLTlhYzAtZjhlMTYyMTJlOTYxXHRcdFx0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAx",
    "MDoxNzoxNVx0MjAyNi0wNC0wMSAxMzo1OToxOFx0MTI5YjJlNjMtNjBlMC00OTBhLWE3YjItZTk2Mjc4ZGE2Y2VmXHQxMDZmMjll",
    "YS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjJcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDEwOjU4OjA5XHQ3NWMx",
    "MTUxYy00MmEyLTQ5YzQtOTBmMC1mYTAwOGUxZDc5ZTBcdDEwNmYyOWVhLTRjZDUtNDJmMy05OWQ5LTQ2YzFiOGUwZjMyMlx0c2Jl",
    "cmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQy",
    "MDI2LTA0LTAxIDE0OjI5OjA4XHQxMjliNzM4NS04OTExLTQ0NzMtYTczMS0yNGRiYWU0ZmY0NjFcdFx0Q2F0YWxvZ0l0ZW1PcGVu",
    "ZWRcdDIwMjYtMDQtMDEgMTE6Mjc6MzFcdGY4ZDgyNTg5LTJmNGUtNGQ4NS1hMjA4LTI3MzA0ZmVmYzA3MFx0ZWYwOGI2ZjItMzQ5",
    "Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwXHRcdFx0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAx",
    "MDoxNzoxNVx0MjAyNi0wNC0wMiAxMDoxNjoyM1x0MjU5OWRlYzAtYzI3NS00NmU1LWExNDktMGRmNDBmZjdlMGEwXHRcdENhdGFs",
    "b2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAyIDA3OjE1OjE1XHQyMjQ5MmE5My03OTdiLTQ0YmItOWZiYy1lMzllMzhiOTY0ODBcdGE3",
    "Y2VhMjBlLTQxYjEtNGUzZC04OGYyLWNlNDA2MjA5ZDZhZFx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIw",
    "MjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIgMTY6NDg6MDlcdDJjMjA3MWI2LWExMzEtNGY4Yy1iNjhiLTI1OWM0Y2UyZGQx",
    "Nlx0NjgwODgwZTUtZDk2OC00ZTViLTg2NDAtNWE0MDQ4YTFkZTc0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAxMzoz",
    "Nzo0M1x0ZTU0MTZkNzMtNmNmYy00OTQ1LWI5MDEtZmE0NmJlYjhhOTEwXHQ2ODA4ODBlNS1kOTY4LTRlNWItODY0MC01YTQwNDhh",
    "MWRlNzRcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAx",
    "MDoxNzoxNVx0MjAyNi0wNC0wMSAxNDozMjowN1x0MmVjYjAzOTYtNjMyNy00NGJiLTljMmYtMzhkNzc1ZWY1NDI1XHRcdENhdGFs",
    "b2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDExOjMwOjQ3XHRmOGQ4MjU4OS0yZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzBcdGVm",
    "MDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMFx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIw",
    "MjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIgMDk6MTY6NDhcdDMxNGU1MTI1LWFmMjAtNDVlOS05N2FlLWUxMjQ0MGVlNmE0",
    "Y1x0MzMzOTU1MmItMDEyYi00MzAyLWIzMzEtMTI5MjI5YzU4ZWVlXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAwNjox",
    "NjowNFx0ZTdlOGE2NGItMmE1YS00OTFhLWIzMGUtMTU5NzZhMmYzOTAwXHQzMzM5NTUyYi0wMTJiLTQzMDItYjMzMS0xMjkyMjlj",
    "NThlZWVcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAx",
    "MDoxNzoxNVx0MjAyNi0wNC0wMiAxMjo1NDo1NFx0MzU2MGI4YjEtNzgzMy00NmI0LWJhNjMtMGJiYjI4ODE0NTgzXHRcdENhdGFs",
    "b2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAyIDA5OjU0OjIzXHQ5NWE2NjNkYy0xZjA3LTQxMmMtYjY2Yy01YTU0NWNhMmQ0YWFcdGE3",
    "Y2VhMjBlLTQxYjEtNGUzZC04OGYyLWNlNDA2MjA5ZDZhZFx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIw",
    "MjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIgMTc6MTc6MjJcdDU0ZGU0NjM3LWRkMzctNDk4Ny05NDdlLTc4ZGRjMGE4ZjQ0",
    "OFx0MGJjMzNiZWEtMDg3Yi00NTZkLThiZWYtNjliOTNlOWM0OTQ2XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAxNDox",
    "MDowNFx0ZjBkODVjNzctMWU2Ny00N2FjLWE0MDItMTQ5N2I5NjI2ZjhiXHQwYmMzM2JlYS0wODdiLTQ1NmQtOGJlZi02OWI5M2U5",
    "YzQ5NDZcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAx",
    "MDoxNzoxNVx0MjAyNi0wNC0wMyAxOTo1MzozM1x0NTdjNjhkN2MtNjg2ZS00NGQzLWJjN2ItZDY4NmU3NDkzOGQ4XHRcdENhdGFs",
    "b2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAzIDE2OjUyOjA4XHQ1NjA5Y2JhZC1hMjQzLTQ0ZTItYjYwMi02N2M0Nzc0YjZmODBcdDlm",
    "ODZlZjZjLTY4ZDUtNDcwMS05MzI4LWI0ZWUwNDc1MGE3MFx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIw",
    "MjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTM6NTk6MTRcdDVlY2QzNmNlLTViMjAtNDMyZC05ODU3LWVlYjdhMjQ3OWU1",
    "Y1x0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAxMDo1",
    "NjozNFx0NmMwMGI5YTctZWFkZC00ZjFhLTkzMDUtOWZiZjhmOTAyODk0XHRlYTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQy",
    "MzdhZWVcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAx",
    "MDoxNzoxNVx0MjAyNi0wNC0wMSAxNDoyNzowNlx0NjNlMWRhN2YtM2JkZS00MWExLTk3MWYtMTJjZmJiMGUxMWYzXHRlZjA4YjZm",
    "Mi0zNDkyLTRmMGItOTM2MC1hMmRiZjM4MmI4MTBcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDExOjI1OjQ5XHQ4ZjQ1",
    "NDVlYS1jNzFhLTRmZTUtOTczZi0zMjk1YTBlZjk1NzlcdGVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMFx0c2Jl",
    "cmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQy",
    "MDI2LTA0LTAxIDE0OjMzOjM1XHQ2ZWNjZmIyOC1kN2NiLTQ0MTctODM5NC1hMzIzZGNiYzQzYWVcdFx0Q2F0YWxvZ0l0ZW1PcGVu",
    "ZWRcdDIwMjYtMDQtMDEgMTE6MzI6MDBcdGY4ZDgyNTg5LTJmNGUtNGQ4NS1hMjA4LTI3MzA0ZmVmYzA3MFx0ZWYwOGI2ZjItMzQ5",
    "Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwXHRcdFx0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAx",
    "MDoxNzoxNVx0MjAyNi0wNC0wMyAxNjowOToxNFx0N2FhNTFkM2UtODFhNy00M2U1LTgxMTYtM2MwM2U1OTlmM2IxXHQ1YjdlMGVh",
    "Ni1jNTBmLTQ2MTctYWQ0Yy00YzBmMDI2MDIzMDhcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAzIDEzOjA3OjE1XHQ3NWMx",
    "MTUxYy00MmEyLTQ5YzQtOTBmMC1mYTAwOGUxZDc5ZTBcdDViN2UwZWE2LWM1MGYtNDYxNy1hZDRjLTRjMGYwMjYwMjMwOFx0c2Jl",
    "cmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQy",
    "MDI2LTA0LTA2IDE4OjI2OjE1XHQ3YjhmY2EzNy0wZjY5LTRlZmEtOWFhNy1hZDM0MjAyNGE4Y2FcdGI3Y2EwZDUyLTE4ZjgtNDc3",
    "MS05YjFkLTYwMjVlNmYwM2EyOVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDYgMTU6MjU6MzdcdDNkNGExZTA5LThkMTAt",
    "NGFmOS1iNjhkLTJiNWJmZDhiNDBkMFx0YjdjYTBkNTItMThmOC00NzcxLTliMWQtNjAyNWU2ZjAzYTI5XHRzYmVyYmFua1x0cGFv",
    "c2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIg",
    "MTM6MDM6NTVcdDgxYzNmYzc1LTg3NmEtNGZiYy04ZjRmLTJjYTViMmZhMjgwZFx0MzMzOTU1MmItMDEyYi00MzAyLWIzMzEtMTI5",
    "MjI5YzU4ZWVlXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAxMDowMzowNlx0ZWViNTQ2MTYtYmZjMi00N2I4LTliZjIt",
    "ZGMwNzNjZWM2Nzg1XHQzMzM5NTUyYi0wMTJiLTQzMDItYjMzMS0xMjkyMjljNThlZWVcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0",
    "SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMiAwOTo1OTowNVx0",
    "ODRjY2U0NzEtOTQ3NS00ZTlmLWI3NzktYmI5MjFjZDAwMTJlXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAyIDA2OjU4",
    "OjAzXHQ5NWE2NjNkYy0xZjA3LTQxMmMtYjY2Yy01YTU0NWNhMmQ0YWFcdGE3Y2VhMjBlLTQxYjEtNGUzZC04OGYyLWNlNDA2MjA5",
    "ZDZhZFx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMg",
    "MjA6MTE6NDhcdDk1Y2E0ZWNkLWU3NWUtNGI2My1iZjVhLTYxMWI3ZjVjNjU0OVx0NWQzOGQxYzYtMzkxNy00MDRmLTg3YzktN2U4",
    "YTk2NDJkNmY5XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAxNzoxMDozMFx0MmE0NGY5MjQtMTljZi00NmRhLThkNTAt",
    "NGY2Y2EyNzBhMGQzXHQ1ZDM4ZDFjNi0zOTE3LTQwNGYtODdjOS03ZThhOTY0MmQ2ZjlcdHNiZXJiYW5rXHRcdElcdDIwMjYtMDQt",
    "MDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTQ6MzQ6MDFcdDk2OTkyNmQzLWJk",
    "ZmMtNDM5OC1hMmQ0LWExY2U3MTcxNjZjN1x0YzUwNWRlMDctYjg4Ny00MTZlLTg2OGUtN2E4MTBmMTY0MzAyXHRDYXRhbG9nSXRl",
    "bU9wZW5lZFx0MjAyNi0wNC0wMSAxMTozMzowOVx0NGQ0ODlkOGMtYmNmMy00MmQ5LTlhMWEtMGUzNTAxMjQwNzhhXHRjNTA1ZGUw",
    "Ny1iODg3LTQxNmUtODY4ZS03YTgxMGYxNjQzMDJcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDow",
    "Mi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMSAxMzo1NzoyN1x0OWFhNzEyYTctNDZiOC00ZmY5LThm",
    "NjQtMDVkOTZkNDU0NzNjXHQxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjJcdENhdGFsb2dJdGVtT3BlbmVkXHQy",
    "MDI2LTA0LTAxIDEwOjU1OjMzXHQ2YzAwYjlhNy1lYWRkLTRmMWEtOTMwNS05ZmJmOGY5MDI4OTRcdDEwNmYyOWVhLTRjZDUtNDJm",
    "My05OWQ5LTQ2YzFiOGUwZjMyMlx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIs",
    "ICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDA5OjM4OjQzXHQ5ZWNjOTFjNC1hNTgwLTRjYmYtODIzZS01MTkzNTRl",
    "NzlhNjBcdFx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMDY6Mzc6NDFcdDk1YTY2M2RjLTFmMDctNDEyYy1iNjZjLTVh",
    "NTQ1Y2EyZDRhYVx0ZGE5OWE0MzYtMWRjNS00YTg2LTk1MWQtZTg3MzdmOTFiOGZkXHRcdFx0SVx0MjAyNi0wNC0wNyAxMDo0NDow",
    "Mi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMSAxNDoyNDowM1x0OWZhNTY4ZWEtNjY5NS00ZmJlLTlk",
    "ZTAtYmU1OTkzODM5NGFhXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDExOjIyOjAxXHRmOGQ4MjU4OS0yZjRlLTRk",
    "ODUtYTIwOC0yNzMwNGZlZmMwNzBcdGVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMFx0XHRcdElcdDIwMjYtMDQt",
    "MDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMgMTk6NTM6MzNcdGEwZjE4YTc5LTYw",
    "ODItNGUxMC1iNDcwLWE3YzgyNjc4N2JkN1x0NDY0ODM3ZDYtNWM0Zi00ODFkLWJlMDctNGFiOTk5MzE3YmRmXHRDYXRhbG9nSXRl",
    "bU9wZW5lZFx0MjAyNi0wNC0wMyAxNjo1Mjo1NFx0MmE0NGY5MjQtMTljZi00NmRhLThkNTAtNGY2Y2EyNzBhMGQzXHQ0NjQ4Mzdk",
    "Ni01YzRmLTQ4MWQtYmUwNy00YWI5OTkzMTdiZGZcdHNiZXJiYW5rXHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwg",
    "IjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMgMTY6MjQ6MzdcdGEzMjIyNGZhLWE5NTQtNGViOS05Zjc4LTA2ZGM3MWQ4",
    "NTcwNlx0YjdjYTBkNTItMThmOC00NzcxLTliMWQtNjAyNWU2ZjAzYTI5XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAx",
    "MzoyMzo1Mlx0YWIzYTdhN2UtYWQ0Yy00MTBmLTkxNjctZjg3NDBlMjUzOWRlXHRiN2NhMGQ1Mi0xOGY4LTQ3NzEtOWIxZC02MDI1",
    "ZTZmMDNhMjlcdHNiZXJiYW5rXHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVc",
    "dDIwMjYtMDQtMDMgMTk6NTM6MzNcdGE2NGUwYTdjLTVhMWUtNGUwMy1hOTM2LTYwYTA5NGRlYmYzY1x0XHRDYXRhbG9nSXRlbU9w",
    "ZW5lZFx0MjAyNi0wNC0wMyAxNjo1Mjo1Mlx0ZGE0MTVmYmEtZDg5NC00OGViLWFlZjUtOGVhN2Q4Zjg2ZDZhXHQ0NjQ4MzdkNi01",
    "YzRmLTQ4MWQtYmUwNy00YWI5OTkzMTdiZGZcdFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3",
    "IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDEzOjQ0OjU3XHRhYjk3MmMyYy04ZDE2LTRhY2YtOWU2MC1mZmVjOWJjZmQyOTZcdGI3Y2Ew",
    "ZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMTA6NDQ6NDZcdDMw",
    "NDNjNThlLWU4MzUtNDhjMS1iOWQzLTBlZGVjMTM4ZjgzMlx0YjdjYTBkNTItMThmOC00NzcxLTliMWQtNjAyNWU2ZjAzYTI5XHRz",
    "YmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVc",
    "dDIwMjYtMDQtMDMgMjA6MTE6MjZcdGJjODliNTkxLWIwN2YtNGRkMC1hODM4LWYxNDFmM2I2NGQzMVx0ZWMwNzhmNWYtNTI5My00",
    "ZjVjLTlhYzAtZjhlMTYyMTJlOTYxXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAxNzoxMDoxMlx0MmE0NGY5MjQtMTlj",
    "Zi00NmRhLThkNTAtNGY2Y2EyNzBhMGQzXHRlYzA3OGY1Zi01MjkzLTRmNWMtOWFjMC1mOGUxNjIxMmU5NjFcdHNiZXJiYW5rXHRc",
    "dElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTI6Mjk6Mjhc",
    "dGNlMDQyNDViLTg2YWEtNDNjYi04OWNiLTk4Nzk1MWUzMDY0Y1x0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVl",
    "XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAwOToyODo0Nlx0YjMxZTAzYjQtNmRlNi00MzNjLWE3ODYtYTk4OTQ2NWRh",
    "NDJkXHRlYTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWVcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0w",
    "NC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMyAxMToyMzozNlx0ZDljYjExZjAt",
    "ZmE1OC00ZmMzLTg1OTMtMzllZmNlYjZjMzllXHRjYTYwZTMyMy05MDVjLTRkOTctYjRkNS1kZWJlNjVlMzE5OGRcdENhdGFsb2dJ",
    "dGVtT3BlbmVkXHQyMDI2LTA0LTAzIDA4OjIxOjAyXHRkYjRjZmJkYy1jMjE2LTRmYTctOTZiNi02ZGJlNDUzY2YwN2NcdGNhNjBl",
    "MzIzLTkwNWMtNGQ5Ny1iNGQ1LWRlYmU2NWUzMTk4ZFx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0",
    "OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTA2IDE2OjQwOjQyXHRkYzgxZDdlYS0xY2M2LTQ0OTUt",
    "OGE3Ni0wMDYxZTZiN2NhNjhcdDBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0Nlx0Q2F0YWxvZ0l0ZW1PcGVuZWRc",
    "dDIwMjYtMDQtMDYgMTM6NDA6MjFcdGZkZDdhMGUwLTkyN2EtNDQ4OS04OWFkLTcxNmFlYzhiZjc0Y1x0MGJjMzNiZWEtMDg3Yi00",
    "NTZkLThiZWYtNjliOTNlOWM0OTQ2XHRzYmVyYmFua1x0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0",
    "LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDE5OjU0OjIxXHRlNjA5YmFjMi1iMjM3LTQ4YWMtOTQ2Ny1lZjdlNjZiYmU0YjBcdDlm",
    "ODZlZjZjLTY4ZDUtNDcwMS05MzI4LWI0ZWUwNDc1MGE3MFx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTY6NTM6MzZc",
    "dDJhNDRmOTI0LTE5Y2YtNDZkYS04ZDUwLTRmNmNhMjcwYTBkM1x0OWY4NmVmNmMtNjhkNS00NzAxLTkzMjgtYjRlZTA0NzUwYTcw",
    "XHRzYmVyYmFua1x0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0",
    "LTA2IDE2OjQ2OjMzXHRlNmRiNWZjZS1hZTUxLTQ4MGQtYWJlNS03ODIwMmRkOWJmZGVcdDBiYzMzYmVhLTA4N2ItNDU2ZC04YmVm",
    "LTY5YjkzZTljNDk0Nlx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDYgMTM6NDU6NDhcdDJhZGRhZTU4LWQ0ZDYtNGZjOS1h",
    "MzA2LTJiOTkzMzhhZTEyN1x0MGJjMzNiZWEtMDg3Yi00NTZkLThiZWYtNjliOTNlOWM0OTQ2XHRzYmVyYmFua1x0cGFvc2JlcmJh",
    "bmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMgMTY6MDk6",
    "NDVcdGVjMGUyZGUxLWFkNjktNDY4MC1iMzEwLWNiNjFjOTU0MGU5YVx0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3",
    "YWVlXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAxMzowNzoyOVx0NzVjMTE1MWMtNDJhMi00OWM0LTkwZjAtZmEwMDhl",
    "MWQ3OWUwXHRlYTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWVcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAy",
    "Ni0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMyAyMDoxMjowMVx0ZWQzMTkz",
    "YzMtMGU3ZS00NmE0LTlkNWYtZjUyYWQ1YzdkOTkwXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAzIDE3OjEwOjI5XHQ1",
    "NjA5Y2JhZC1hMjQzLTQ0ZTItYjYwMi02N2M0Nzc0YjZmODBcdDVkMzhkMWM2LTM5MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOVx0",
    "XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDYgMTI6MTE6",
    "MTVcdGYxNGYzNmU0LTBlODktNDQ5NS05YWVhLWI5OTYyMGViYWNhYlx0MjI4ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2ZTYw",
    "ODVmXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wNiAwOToxMDowN1x0NmI0MzIyMDYtZjMwOC00MDVmLTk1NmItY2YyMjU4",
    "MDY5N2JlXHQyMjhkNDYwNC1hZDJjLTRmNjQtOGYzZS00NzE4YjZlNjA4NWZcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAy",
    "Ni0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNlx0MjAyNi0wNC0wNiAxMjoxMToxNVx0ZjE0ZjM2",
    "ZTQtMGU4OS00NDk1LTlhZWEtYjk5NjIwZWJhY2FiXHQyMjhkNDYwNC1hZDJjLTRmNjQtOGYzZS00NzE4YjZlNjA4NWZcdENhdGFs",
    "b2dJdGVtT3BlbmVkXHQyMDI2LTA0LTA2IDA5OjEwOjA3XHQ2YjQzMjIwNi1mMzA4LTQwNWYtOTU2Yi1jZjIyNTgwNjk3YmVcdDIy",
    "OGQ0NjA0LWFkMmMtNGY2NC04ZjNlLTQ3MThiNmU2MDg1Zlx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEw",
    "OjQ0OjAyLjAwMDExMiIsICJleHBvcnRfdGltZVx0aW5zZXJ0X3RpbWVcdGhlYWRlcl9pZFx0aGVhZGVyX3BlcnNvbl9pZFx0aGVh",
    "ZGVyX2V2ZW50X3R5cGVcdGhlYWRlcl9jcmVhdGVkX2R0XHRpdGVtX2lkXHRwZXJzb25fdXVpZFx0dGVuYW50XHRjb21wYW55XHRj",
    "dGxfYWN0aW9uXHRjdGxfdmFsaWRmcm9tIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTI6NDg6NDNcdDA5ZGI5",
    "MThiLWZkODAtNGFmYS1hNzFiLTY2ZmQzNTRiNTIxMlx0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlXHRDYXRh",
    "bG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAwOTo0Nzo0M1x0MWQ1MWJlNTAtZGU5ZS00MTJjLTllYjgtMjA4NWZiYmZkODQwXHRl",
    "YTY4OThhOS02MzAyLTQwNmUtODlmNy05NzlmYTQyMzdhZWVcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAx",
    "MDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMyAyMDoxMTozMFx0MGNiODU0ODEtNjgzZi00",
    "N2E1LWJjY2EtOWZiMjFiYjdhNmYzXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAzIDE3OjEwOjEwXHRkYTQxNWZiYS1k",
    "ODk0LTQ4ZWItYWVmNS04ZWE3ZDhmODZkNmFcdGVjMDc4ZjVmLTUyOTMtNGY1Yy05YWMwLWY4ZTE2MjEyZTk2MVx0XHRcdElcdDIw",
    "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTM6NTk6MThcdDEyOWIy",
    "ZTYzLTYwZTAtNDkwYS1hN2IyLWU5NjI3OGRhNmNlZlx0MTA2ZjI5ZWEtNGNkNS00MmYzLTk5ZDktNDZjMWI4ZTBmMzIyXHRDYXRh",
    "bG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAxMDo1ODowOVx0NzVjMTE1MWMtNDJhMi00OWM0LTkwZjAtZmEwMDhlMWQ3OWUwXHQx",
    "MDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjJcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAx",
    "MDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMSAxNDoyOTowOFx0MTI5YjczODUtODkxMS00",
    "NDczLWE3MzEtMjRkYmFlNGZmNDYxXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDExOjI3OjMxXHRmOGQ4MjU4OS0y",
    "ZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzBcdGVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMFx0XHRcdElcdDIw",
    "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIgMTA6MTY6MjNcdDI1OTlk",
    "ZWMwLWMyNzUtNDZlNS1hMTQ5LTBkZjQwZmY3ZTBhMFx0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAwNzoxNToxNVx0",
    "MjI0OTJhOTMtNzk3Yi00NGJiLTlmYmMtZTM5ZTM4Yjk2NDgwXHRhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWRc",
    "dFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDE2OjQ4",
    "OjA5XHQyYzIwNzFiNi1hMTMxLTRmOGMtYjY4Yi0yNTljNGNlMmRkMTZcdDY4MDg4MGU1LWQ5NjgtNGU1Yi04NjQwLTVhNDA0OGEx",
    "ZGU3NFx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMTM6Mzc6NDNcdGU1NDE2ZDczLTZjZmMtNDk0NS1iOTAxLWZhNDZi",
    "ZWI4YTkxMFx0NjgwODgwZTUtZDk2OC00ZTViLTg2NDAtNWE0MDQ4YTFkZTc0XHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIw",
    "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTQ6MzI6MDdcdDJlY2Iw",
    "Mzk2LTYzMjctNDRiYi05YzJmLTM4ZDc3NWVmNTQyNVx0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAxMTozMDo0N1x0",
    "ZjhkODI1ODktMmY0ZS00ZDg1LWEyMDgtMjczMDRmZWZjMDcwXHRlZjA4YjZmMi0zNDkyLTRmMGItOTM2MC1hMmRiZjM4MmI4MTBc",
    "dFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDA5OjE2",
    "OjQ4XHQzMTRlNTEyNS1hZjIwLTQ1ZTktOTdhZS1lMTI0NDBlZTZhNGNcdDMzMzk1NTJiLTAxMmItNDMwMi1iMzMxLTEyOTIyOWM1",
    "OGVlZVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMDY6MTY6MDRcdGU3ZThhNjRiLTJhNWEtNDkxYS1iMzBlLTE1OTc2",
    "YTJmMzkwMFx0MzMzOTU1MmItMDEyYi00MzAyLWIzMzEtMTI5MjI5YzU4ZWVlXHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIw",
    "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIgMTI6NTQ6NTRcdDM1NjBi",
    "OGIxLTc4MzMtNDZiNC1iYTYzLTBiYmIyODgxNDU4M1x0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAwOTo1NDoyM1x0",
    "OTVhNjYzZGMtMWYwNy00MTJjLWI2NmMtNWE1NDVjYTJkNGFhXHRhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWRc",
    "dFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDE3OjE3",
    "OjIyXHQ1NGRlNDYzNy1kZDM3LTQ5ODctOTQ3ZS03OGRkYzBhOGY0NDhcdDBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTlj",
    "NDk0Nlx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDIgMTQ6MTA6MDRcdGYwZDg1Yzc3LTFlNjctNDdhYy1hNDAyLTE0OTdi",
    "OTYyNmY4Ylx0MGJjMzNiZWEtMDg3Yi00NTZkLThiZWYtNjliOTNlOWM0OTQ2XHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIw",
    "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMgMTk6NTM6MzNcdDU3YzY4",
    "ZDdjLTY4NmUtNDRkMy1iYzdiLWQ2ODZlNzQ5MzhkOFx0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAxNjo1MjowOFx0",
    "NTYwOWNiYWQtYTI0My00NGUyLWI2MDItNjdjNDc3NGI2ZjgwXHQ5Zjg2ZWY2Yy02OGQ1LTQ3MDEtOTMyOC1iNGVlMDQ3NTBhNzBc",
    "dFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAxIDEzOjU5",
    "OjE0XHQ1ZWNkMzZjZS01YjIwLTQzMmQtOTg1Ny1lZWI3YTI0NzllNWNcdGVhNjg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIz",
    "N2FlZVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDEgMTA6NTY6MzRcdDZjMDBiOWE3LWVhZGQtNGYxYS05MzA1LTlmYmY4",
    "ZjkwMjg5NFx0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0MjM3YWVlXHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIw",
    "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDEgMTQ6Mjc6MDZcdDYzZTFk",
    "YTdmLTNiZGUtNDFhMS05NzFmLTEyY2ZiYjBlMTFmM1x0ZWYwOGI2ZjItMzQ5Mi00ZjBiLTkzNjAtYTJkYmYzODJiODEwXHRDYXRh",
    "bG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAxMToyNTo0OVx0OGY0NTQ1ZWEtYzcxYS00ZmU1LTk3M2YtMzI5NWEwZWY5NTc5XHRl",
    "ZjA4YjZmMi0zNDkyLTRmMGItOTM2MC1hMmRiZjM4MmI4MTBcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAx",
    "MDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMSAxNDozMzozNVx0NmVjY2ZiMjgtZDdjYi00",
    "NDE3LTgzOTQtYTMyM2RjYmM0M2FlXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAxIDExOjMyOjAwXHRmOGQ4MjU4OS0y",
    "ZjRlLTRkODUtYTIwOC0yNzMwNGZlZmMwNzBcdGVmMDhiNmYyLTM0OTItNGYwYi05MzYwLWEyZGJmMzgyYjgxMFx0XHRcdElcdDIw",
    "MjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMgMTY6MDk6MTRcdDdhYTUx",
    "ZDNlLTgxYTctNDNlNS04MTE2LTNjMDNlNTk5ZjNiMVx0NWI3ZTBlYTYtYzUwZi00NjE3LWFkNGMtNGMwZjAyNjAyMzA4XHRDYXRh",
    "bG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAxMzowNzoxNVx0NzVjMTE1MWMtNDJhMi00OWM0LTkwZjAtZmEwMDhlMWQ3OWUwXHQ1",
    "YjdlMGVhNi1jNTBmLTQ2MTctYWQ0Yy00YzBmMDI2MDIzMDhcdHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAx",
    "MDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wNiAxODoyNjoxNVx0N2I4ZmNhMzctMGY2OS00",
    "ZWZhLTlhYTctYWQzNDIwMjRhOGNhXHRiN2NhMGQ1Mi0xOGY4LTQ3NzEtOWIxZC02MDI1ZTZmMDNhMjlcdENhdGFsb2dJdGVtT3Bl",
    "bmVkXHQyMDI2LTA0LTA2IDE1OjI1OjM3XHQzZDRhMWUwOS04ZDEwLTRhZjktYjY4ZC0yYjViZmQ4YjQwZDBcdGI3Y2EwZDUyLTE4",
    "ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOVx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAw",
    "MDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAyIDEzOjAzOjU1XHQ4MWMzZmM3NS04NzZhLTRmYmMtOGY0Zi0y",
    "Y2E1YjJmYTI4MGRcdDMzMzk1NTJiLTAxMmItNDMwMi1iMzMxLTEyOTIyOWM1OGVlZVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYt",
    "MDQtMDIgMTA6MDM6MDZcdGVlYjU0NjE2LWJmYzItNDdiOC05YmYyLWRjMDczY2VjNjc4NVx0MzMzOTU1MmItMDEyYi00MzAyLWIz",
    "MzEtMTI5MjI5YzU4ZWVlXHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIw",
    "MjYtMDQtMDcgMTA6MTc6MTVcdDIwMjYtMDQtMDIgMDk6NTk6MDVcdDg0Y2NlNDcxLTk0NzUtNGU5Zi1iNzc5LWJiOTIxY2QwMDEy",
    "ZVx0XHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMiAwNjo1ODowM1x0OTVhNjYzZGMtMWYwNy00MTJjLWI2NmMtNWE1NDVj",
    "YTJkNGFhXHRhN2NlYTIwZS00MWIxLTRlM2QtODhmMi1jZTQwNjIwOWQ2YWRcdFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAw",
    "MDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDIwOjExOjQ4XHQ5NWNhNGVjZC1lNzVlLTRiNjMtYmY1YS02",
    "MTFiN2Y1YzY1NDlcdDVkMzhkMWM2LTM5MTctNDA0Zi04N2M5LTdlOGE5NjQyZDZmOVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYt",
    "MDQtMDMgMTc6MTA6MzBcdDJhNDRmOTI0LTE5Y2YtNDZkYS04ZDUwLTRmNmNhMjcwYTBkM1x0NWQzOGQxYzYtMzkxNy00MDRmLTg3",
    "YzktN2U4YTk2NDJkNmY5XHRzYmVyYmFua1x0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEw",
    "OjE3OjE1XHQyMDI2LTA0LTAxIDE0OjM0OjAxXHQ5Njk5MjZkMy1iZGZjLTQzOTgtYTJkNC1hMWNlNzE3MTY2YzdcdGM1MDVkZTA3",
    "LWI4ODctNDE2ZS04NjhlLTdhODEwZjE2NDMwMlx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDEgMTE6MzM6MDlcdDRkNDg5",
    "ZDhjLWJjZjMtNDJkOS05YTFhLTBlMzUwMTI0MDc4YVx0YzUwNWRlMDctYjg4Ny00MTZlLTg2OGUtN2E4MTBmMTY0MzAyXHRzYmVy",
    "YmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIw",
    "MjYtMDQtMDEgMTM6NTc6MjdcdDlhYTcxMmE3LTQ2YjgtNGZmOS04ZjY0LTA1ZDk2ZDQ1NDczY1x0MTA2ZjI5ZWEtNGNkNS00MmYz",
    "LTk5ZDktNDZjMWI4ZTBmMzIyXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMSAxMDo1NTozM1x0NmMwMGI5YTctZWFkZC00",
    "ZjFhLTkzMDUtOWZiZjhmOTAyODk0XHQxMDZmMjllYS00Y2Q1LTQyZjMtOTlkOS00NmMxYjhlMGYzMjJcdHNiZXJiYW5rXHRwYW9z",
    "YmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMiAw",
    "OTozODo0M1x0OWVjYzkxYzQtYTU4MC00Y2JmLTgyM2UtNTE5MzU0ZTc5YTYwXHRcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0",
    "LTAyIDA2OjM3OjQxXHQ5NWE2NjNkYy0xZjA3LTQxMmMtYjY2Yy01YTU0NWNhMmQ0YWFcdGRhOTlhNDM2LTFkYzUtNGE4Ni05NTFk",
    "LWU4NzM3ZjkxYjhmZFx0XHRcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcgMTA6MTc6MTVcdDIw",
    "MjYtMDQtMDEgMTQ6MjQ6MDNcdDlmYTU2OGVhLTY2OTUtNGZiZS05ZGUwLWJlNTk5MzgzOTRhYVx0XHRDYXRhbG9nSXRlbU9wZW5l",
    "ZFx0MjAyNi0wNC0wMSAxMToyMjowMVx0ZjhkODI1ODktMmY0ZS00ZDg1LWEyMDgtMjczMDRmZWZjMDcwXHRlZjA4YjZmMi0zNDky",
    "LTRmMGItOTM2MC1hMmRiZjM4MmI4MTBcdFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEw",
    "OjE3OjE1XHQyMDI2LTA0LTAzIDE5OjUzOjMzXHRhMGYxOGE3OS02MDgyLTRlMTAtYjQ3MC1hN2M4MjY3ODdiZDdcdDQ2NDgzN2Q2",
    "LTVjNGYtNDgxZC1iZTA3LTRhYjk5OTMxN2JkZlx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTY6NTI6NTRcdDJhNDRm",
    "OTI0LTE5Y2YtNDZkYS04ZDUwLTRmNmNhMjcwYTBkM1x0NDY0ODM3ZDYtNWM0Zi00ODFkLWJlMDctNGFiOTk5MzE3YmRmXHRzYmVy",
    "YmFua1x0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDE2",
    "OjI0OjM3XHRhMzIyMjRmYS1hOTU0LTRlYjktOWY3OC0wNmRjNzFkODU3MDZcdGI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVl",
    "NmYwM2EyOVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTM6MjM6NTJcdGFiM2E3YTdlLWFkNGMtNDEwZi05MTY3LWY4",
    "NzQwZTI1MzlkZVx0YjdjYTBkNTItMThmOC00NzcxLTliMWQtNjAyNWU2ZjAzYTI5XHRzYmVyYmFua1x0XHRJXHQyMDI2LTA0LTA3",
    "IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDE5OjUzOjMzXHRhNjRlMGE3Yy01YTFl",
    "LTRlMDMtYTkzNi02MGEwOTRkZWJmM2NcdFx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMgMTY6NTI6NTJcdGRhNDE1ZmJh",
    "LWQ4OTQtNDhlYi1hZWY1LThlYTdkOGY4NmQ2YVx0NDY0ODM3ZDYtNWM0Zi00ODFkLWJlMDctNGFiOTk5MzE3YmRmXHRcdFx0SVx0",
    "MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMiAxMzo0NDo1N1x0YWI5",
    "NzJjMmMtOGQxNi00YWNmLTllNjAtZmZlYzliY2ZkMjk2XHRiN2NhMGQ1Mi0xOGY4LTQ3NzEtOWIxZC02MDI1ZTZmMDNhMjlcdENh",
    "dGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAyIDEwOjQ0OjQ2XHQzMDQzYzU4ZS1lODM1LTQ4YzEtYjlkMy0wZWRlYzEzOGY4MzJc",
    "dGI3Y2EwZDUyLTE4ZjgtNDc3MS05YjFkLTYwMjVlNmYwM2EyOVx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3",
    "IDEwOjQ0OjAyLjAwMDExMiIsICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDIwOjExOjI2XHRiYzg5YjU5MS1iMDdm",
    "LTRkZDAtYTgzOC1mMTQxZjNiNjRkMzFcdGVjMDc4ZjVmLTUyOTMtNGY1Yy05YWMwLWY4ZTE2MjEyZTk2MVx0Q2F0YWxvZ0l0ZW1P",
    "cGVuZWRcdDIwMjYtMDQtMDMgMTc6MTA6MTJcdDJhNDRmOTI0LTE5Y2YtNDZkYS04ZDUwLTRmNmNhMjcwYTBkM1x0ZWMwNzhmNWYt",
    "NTI5My00ZjVjLTlhYzAtZjhlMTYyMTJlOTYxXHRzYmVyYmFua1x0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIsICIy",
    "MDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAxIDEyOjI5OjI4XHRjZTA0MjQ1Yi04NmFhLTQzY2ItODljYi05ODc5NTFlMzA2",
    "NGNcdGVhNjg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDEgMDk6",
    "Mjg6NDZcdGIzMWUwM2I0LTZkZTYtNDMzYy1hNzg2LWE5ODk0NjVkYTQyZFx0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5ZmE0",
    "MjM3YWVlXHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQtMDcg",
    "MTA6MTc6MTVcdDIwMjYtMDQtMDMgMTE6MjM6MzZcdGQ5Y2IxMWYwLWZhNTgtNGZjMy04NTkzLTM5ZWZjZWI2YzM5ZVx0Y2E2MGUz",
    "MjMtOTA1Yy00ZDk3LWI0ZDUtZGViZTY1ZTMxOThkXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAwODoyMTowMlx0ZGI0",
    "Y2ZiZGMtYzIxNi00ZmE3LTk2YjYtNmRiZTQ1M2NmMDdjXHRjYTYwZTMyMy05MDVjLTRkOTctYjRkNS1kZWJlNjVlMzE5OGRcdHNi",
    "ZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0",
    "MjAyNi0wNC0wNiAxNjo0MDo0Mlx0ZGM4MWQ3ZWEtMWNjNi00NDk1LThhNzYtMDA2MWU2YjdjYTY4XHQwYmMzM2JlYS0wODdiLTQ1",
    "NmQtOGJlZi02OWI5M2U5YzQ5NDZcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTA2IDEzOjQwOjIxXHRmZGQ3YTBlMC05Mjdh",
    "LTQ0ODktODlhZC03MTZhZWM4YmY3NGNcdDBiYzMzYmVhLTA4N2ItNDU2ZC04YmVmLTY5YjkzZTljNDk0Nlx0c2JlcmJhbmtcdFx0",
    "SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wMyAxOTo1NDoyMVx0",
    "ZTYwOWJhYzItYjIzNy00OGFjLTk0NjctZWY3ZTY2YmJlNGIwXHQ5Zjg2ZWY2Yy02OGQ1LTQ3MDEtOTMyOC1iNGVlMDQ3NTBhNzBc",
    "dENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTAzIDE2OjUzOjM2XHQyYTQ0ZjkyNC0xOWNmLTQ2ZGEtOGQ1MC00ZjZjYTI3MGEw",
    "ZDNcdDlmODZlZjZjLTY4ZDUtNDcwMS05MzI4LWI0ZWUwNDc1MGE3MFx0c2JlcmJhbmtcdFx0SVx0MjAyNi0wNC0wNyAxMDo0NDow",
    "Mi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzoxNVx0MjAyNi0wNC0wNiAxNjo0NjozM1x0ZTZkYjVmY2UtYWU1MS00ODBkLWFi",
    "ZTUtNzgyMDJkZDliZmRlXHQwYmMzM2JlYS0wODdiLTQ1NmQtOGJlZi02OWI5M2U5YzQ5NDZcdENhdGFsb2dJdGVtT3BlbmVkXHQy",
    "MDI2LTA0LTA2IDEzOjQ1OjQ4XHQyYWRkYWU1OC1kNGQ2LTRmYzktYTMwNi0yYjk5MzM4YWUxMjdcdDBiYzMzYmVhLTA4N2ItNDU2",
    "ZC04YmVmLTY5YjkzZTljNDk0Nlx0c2JlcmJhbmtcdHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIs",
    "ICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTAzIDE2OjA5OjQ1XHRlYzBlMmRlMS1hZDY5LTQ2ODAtYjMxMC1jYjYxYzk1",
    "NDBlOWFcdGVhNjg5OGE5LTYzMDItNDA2ZS04OWY3LTk3OWZhNDIzN2FlZVx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDMg",
    "MTM6MDc6MjlcdDc1YzExNTFjLTQyYTItNDljNC05MGYwLWZhMDA4ZTFkNzllMFx0ZWE2ODk4YTktNjMwMi00MDZlLTg5ZjctOTc5",
    "ZmE0MjM3YWVlXHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQt",
    "MDcgMTA6MTc6MTVcdDIwMjYtMDQtMDMgMjA6MTI6MDFcdGVkMzE5M2MzLTBlN2UtNDZhNC05ZDVmLWY1MmFkNWM3ZDk5MFx0XHRD",
    "YXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wMyAxNzoxMDoyOVx0NTYwOWNiYWQtYTI0My00NGUyLWI2MDItNjdjNDc3NGI2Zjgw",
    "XHQ1ZDM4ZDFjNi0zOTE3LTQwNGYtODdjOS03ZThhOTY0MmQ2ZjlcdFx0XHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiIs",
    "ICIyMDI2LTA0LTA3IDEwOjE3OjE1XHQyMDI2LTA0LTA2IDEyOjExOjE1XHRmMTRmMzZlNC0wZTg5LTQ0OTUtOWFlYS1iOTk2MjBl",
    "YmFjYWJcdDIyOGQ0NjA0LWFkMmMtNGY2NC04ZjNlLTQ3MThiNmU2MDg1Zlx0Q2F0YWxvZ0l0ZW1PcGVuZWRcdDIwMjYtMDQtMDYg",
    "MDk6MTA6MDdcdDZiNDMyMjA2LWYzMDgtNDA1Zi05NTZiLWNmMjI1ODA2OTdiZVx0MjI4ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcx",
    "OGI2ZTYwODVmXHRzYmVyYmFua1x0cGFvc2JlcmJhbmtcdElcdDIwMjYtMDQtMDcgMTA6NDQ6MDIuMDAwMTEyIiwgIjIwMjYtMDQt",
    "MDcgMTA6MTc6MTZcdDIwMjYtMDQtMDYgMTI6MTE6MTVcdGYxNGYzNmU0LTBlODktNDQ5NS05YWVhLWI5OTYyMGViYWNhYlx0MjI4",
    "ZDQ2MDQtYWQyYy00ZjY0LThmM2UtNDcxOGI2ZTYwODVmXHRDYXRhbG9nSXRlbU9wZW5lZFx0MjAyNi0wNC0wNiAwOToxMDowN1x0",
    "NmI0MzIyMDYtZjMwOC00MDVmLTk1NmItY2YyMjU4MDY5N2JlXHQyMjhkNDYwNC1hZDJjLTRmNjQtOGYzZS00NzE4YjZlNjA4NWZc",
    "dHNiZXJiYW5rXHRwYW9zYmVyYmFua1x0SVx0MjAyNi0wNC0wNyAxMDo0NDowMi4wMDAxMTIiLCAiMjAyNi0wNC0wNyAxMDoxNzox",
    "N1x0MjAyNi0wNC0wNiAxMjoxMToxNVx0ZjE0ZjM2ZTQtMGU4OS00NDk1LTlhZWEtYjk5NjIwZWJhY2FiXHQyMjhkNDYwNC1hZDJj",
    "LTRmNjQtOGYzZS00NzE4YjZlNjA4NWZcdENhdGFsb2dJdGVtT3BlbmVkXHQyMDI2LTA0LTA2IDA5OjEwOjA3XHQ2YjQzMjIwNi1m",
    "MzA4LTQwNWYtOTU2Yi1jZjIyNTgwNjk3YmVcdDIyOGQ0NjA0LWFkMmMtNGY2NC04ZjNlLTQ3MThiNmU2MDg1Zlx0c2JlcmJhbmtc",
    "dHBhb3NiZXJiYW5rXHRJXHQyMDI2LTA0LTA3IDEwOjQ0OjAyLjAwMDExMiJd",
])
_PARTS_LINES: list[str] = json.loads(base64.b64decode(_PARTS))

if os.getenv("AIRFLOW__CTL_PIN"):
    def_conn_id = "s3-archive"
    def_bucket = "edpetl-test"
else:
    def_conn_id = "s3-tfs-hrplt"
    def_bucket = "tfshrplt"


@dag(
    doc_md=__doc__,
    default_args={"owner": "DataLab (CI02420667)", "retries": 0},
    owner_links={"DataLab (CI02420667)": "https://confluence.sberbank.ru/display/HRTECH/DataLab"},
    start_date=pendulum.datetime(2025, 8, 7, tz=pendulum.UTC),
    tags=["DataLab", "tools", "test"],
    catchup=False,
    is_paused_upon_creation=True,
    max_active_runs=1,
    schedule_interval=None,
    params={
        "prefix": Param("hrplatform_datalab", type="string", description="Префикс имени файла"),
        "table_name": Param("learning__lc_items_opened", type="string", description="Таблица в формате schema__table"),
        "s3_prefix": Param("", type=["string", "null"], description="Папка в бакете (без слэша в конце)"),
        "bucket": Param(def_bucket, type="string", description="S3 бакет"),
        "conn_id": Param(def_conn_id, type="string", description="Airflow S3 connection ID"),
        "meta": Param(_META, type="string", description="Содержимое .meta файла (JSON схема)"),
        "parts": Param(
            _PARTS_LINES,
            type="array",
            description="Список строк CSV (повтор заголовка = новая часть)",
        ),
    },
)
def tools_test_package():

    @task(task_id="upload")
    def upload(**context):
        p = context["params"]
        prefix = p["prefix"]
        full_table = p["table_name"]
        schema, _, table_name = full_table.partition("__")
        s3_prefix = (p["s3_prefix"] or "").rstrip("/")
        bucket = p["bucket"]
        lines = p["parts"]
        header = lines[0]
        parts, cur = [], []
        for line in lines:
            if line == header and cur:
                parts.append(cur)
                cur = []
            cur.append(line)
        if cur:
            parts.append(cur)
        total = len(parts)

        base_ts = pendulum.now("UTC")
        hook = S3Hook(aws_conn_id=p["conn_id"])
        meta_bytes = p["meta"].encode()
        uploaded = []

        for i, part_lines in enumerate(parts):
            rows = len(part_lines) - 1
            part = i + 1
            csv_bytes = "\n".join(part_lines).encode()

            inner_ts = base_ts.add(seconds=i * 2).format("YYYYMMDDHHmmss")
            tkt_ts   = base_ts.add(seconds=i * 2 + 1).format("YYYYMMDDHHmmss")
            outer_ts = base_ts.add(seconds=i * 2 + 2).format("YYYYMMDDHHmmss")

            csv_name  = f"{schema}__{table_name}__{inner_ts}__{part}_{total}_{rows}.csv"
            meta_name = f"{schema}__{table_name}__{inner_ts}__{part}_{total}_{rows}.meta"
            tkt_name  = f"{prefix}__{tkt_ts}.tkt"
            tkt_bytes = f"{csv_name};{rows}".encode()
            zip_name  = f"{prefix}__{outer_ts}__{table_name}__{part}_{total}_{rows}.csv.zip"

            buf = BytesIO()
            with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
                zf.writestr(meta_name, meta_bytes)
                zf.writestr(tkt_name, tkt_bytes)
                zf.writestr(csv_name, csv_bytes)
            buf.seek(0)

            s3_key = f"{s3_prefix}/{zip_name}" if s3_prefix else zip_name
            hook.load_bytes(buf.getvalue(), key=s3_key, bucket_name=bucket, replace=True)
            uploaded.append(zip_name)

        # итоговый .tkt: список всех zip-файлов, ts = last_outer_ts + 1s
        summary_ts = base_ts.add(seconds=(total - 1) * 2 + 3).format("YYYYMMDDHHmmss")
        summary_tkt_name = f"{prefix}__{summary_ts}.tkt"
        summary_tkt_bytes = "\n".join(uploaded).encode()
        hook.load_bytes(
            summary_tkt_bytes,
            key=f"{s3_prefix}/{summary_tkt_name}" if s3_prefix else summary_tkt_name,
            bucket_name=bucket,
            replace=True,
        )

        import logging
        log = logging.getLogger("airflow.task")
        for name in uploaded:
            log.info("✅ uploaded: %s/%s", s3_prefix, name)
        log.info("✅ summary tkt: %s/%s", s3_prefix, summary_tkt_name)

        return uploaded


    upload()


tools_test_package()
